#!/usr/bin/env node
// Writes content/docs/reference/*.mdx from the LuaLS annotations in wax/types/*.lua, and the same
// model as lib/explorer-wax.json for the Explorer page.
// Runs before `dev` and `build`. When the type files are not there (the published repository
// holds only this folder) it does nothing, and the committed files are used as they are.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DOCS = path.resolve(HERE, '..');
const TYPES = process.env.WAX_TYPES_DIR
  ? path.resolve(process.env.WAX_TYPES_DIR)
  : path.resolve(DOCS, '..', 'wax', 'types');
// The type files of the Wax that players can download now (a clone of the public source at its last release).
// What is in TYPES and not in here is newer than the release, and is marked so wherever it is listed.
const RELEASED_TYPES = process.env.WAX_RELEASED_TYPES_DIR
  ? path.resolve(process.env.WAX_RELEASED_TYPES_DIR)
  : path.resolve(DOCS, '..', 'build', 'icarus-wax-repo', 'wax', 'types');
const OUT = path.join(DOCS, 'content', 'docs', 'reference');
const ROUTE = '/docs/reference';
const MARKER = 'Generated by scripts/generate-api.mjs';

// The line a page gets under its title when everything on it is newer than the released Wax (components/next-version.tsx).
const NEXT = '<NextVersion />';
// The small mark on one entry that is newer, where the rest of its page is not, and the line that explains the mark.
const NEXT_MARK = '<NextMark />';
const NEXT_MARK_LINE = '<NextMark block />';
const NEXT_LEGEND = '<NextLegend />';
// One page per type file. A file not listed here still gets a page, named after the file.
// `note` is a line of MDX written at the top of the page.
const PAGES = {
  'ui.lua': {
    slug: 'ui',
    icon: 'PanelTop',
    title: 'ui',
    description: 'Windows, overlays, notifications, hotkeys, themes and icons: everything under ui.',
    lead: ['WaxUI'],
  },
  'controls.lua': {
    slug: 'controls',
    icon: 'SlidersHorizontal',
    title: 'Controls',
    description: 'Every control you can add to a window, a page, a section, a row or an overlay.',
    lead: ['WaxContainer', 'WaxControl'],
  },
  'game.lua': {
    slug: 'game',
    icon: 'Globe',
    title: 'game',
    description: 'The game tree: game, game.Players and the Instances they give you.',
    lead: ['WaxGame'],
  },
  'task.lua': {
    slug: 'tasks',
    icon: 'Timer',
    title: 'Tasks and signals',
    description: 'task for running code alongside the game, and Signal for events.',
    lead: ['WaxTask'],
  },
  'mod.lua': {
    slug: 'mods',
    icon: 'Package',
    title: 'Mods',
    description: 'What every mod has: mod, log, print, persist, storage, require and raw.',
    deprecatedTitle: 'Blocked functions',
    deprecatedIntro:
      'These UE4SS functions raise an error when a mod calls them. The reason is given for each one.',
  },
  'character.lua': {
    slug: 'character',
    icon: 'User',
    title: 'Characters',
    description: 'The fields Wax gives every character, and game.Me for your own.',
    lead: ['WaxMe'],
  },
  'stats.lua': {
    slug: 'stats',
    icon: 'Activity',
    title: 'Stats and modifiers',
    description: 'The numbers the game keeps for a character, and the effects that are on it.',
    lead: ['WaxCharacterStats'],
  },
  'session.lua': {
    slug: 'session',
    icon: 'Clock',
    title: 'Time, weather and the prospect',
    description: 'game.Time, game.Weather, game.Prospect and the players of the session.',
    lead: ['WaxTime', 'WaxWeather', 'WaxProspect'],
  },
  'items.lua': {
    slug: 'items',
    icon: 'Backpack',
    title: 'Items and inventories',
    description: 'What a kind of item is, and what an inventory or a character holds.',
    lead: ['WaxItems'],
  },
  'creature.lua': {
    slug: 'creature',
    icon: 'PawPrint',
    title: 'Creatures',
    description: 'The fields Wax gives every creature, and what the tables of the game say about a kind.',
    lead: ['WaxCreatureMembers'],
  },
  'data.lua': {
    slug: 'data',
    icon: 'Database',
    title: 'Game tables',
    description: 'game.Data: the game\'s own tables of recipes, items, creatures and the rest, read and changed from Lua.',
    lead: ['WaxData'],
  },
  'recipes.lua': {
    slug: 'recipes',
    icon: 'Hammer',
    title: 'Recipes',
    description: 'game.Recipes: finding crafting recipes and changing what they take, give and where they are made.',
    lead: ['WaxRecipes'],
  },
  'workshop.lua': {
    slug: 'workshop',
    icon: 'Store',
    title: 'The store',
    description: 'game.Workshop: the store where exotics are spent, its categories, nodes and prices.',
    lead: ['WaxWorkshop'],
  },
  'assets.lua': {
    slug: 'assets',
    icon: 'Boxes',
    title: 'Assets',
    description: 'game.Assets: loading the game\'s assets by path, and making textures, materials and shapes.',
    lead: ['WaxAssets'],
  },
  'blueprints.lua': {
    slug: 'blueprints',
    icon: 'Box',
    title: 'Blueprints',
    description: 'game.Blueprints: things described in Lua and spawned into the world, and their parts.',
    lead: ['WaxBlueprints'],
  },
  'creature_models.lua': {
    slug: 'creature-models',
    icon: 'Rotate3d',
    title: 'Creature models',
    description: 'What game.Creatures:GetModel gives: the mesh, coat and walk of a creature, for the 3D model control.',
    lead: ['WaxCreatureModel'],
  },
  'watch.lua': {
    slug: 'watch',
    icon: 'Eye',
    title: 'Watching values',
    description: 'game.Frame, and signals that fire when a value of the game changes.',
    lead: ['WaxFrameSignal'],
  },
};
// Lua's own standard library, written by the language server. Not part of Wax.
const SKIP = new Set(['lua_basic.lua']);
const IGNORED_TAGS = new Set(['meta']);

const EXPLORER_OUT = path.join(DOCS, 'lib', 'explorer-wax.json');
// The game's own types, so that a mention of one links to its entry in the Explorer.
const EXPLORER_STAMP = path.join(DOCS, 'lib', 'explorer-stamp.json');
const GAME_TYPES = path.join(
  DOCS,
  'public',
  'explorer-data',
  fs.existsSync(EXPLORER_STAMP) ? JSON.parse(fs.readFileSync(EXPLORER_STAMP, 'utf8')).stamp : '',
  'search.json',
);
const gameTypes = new Set(fs.existsSync(GAME_TYPES) ? JSON.parse(fs.readFileSync(GAME_TYPES, 'utf8')).types.map(([name]) => name) : []);
// What a class name looks like in a sentence: two words run together, or words joined by underscores. Not inside quotes.
const GAME_WORD = /(?<![\w."'/#=-])(Actor|Pawn|Object|[A-Z][a-z0-9]+(?:[A-Z]+[a-z0-9]*)+|[A-Za-z][A-Za-z0-9]*(?:_[A-Za-z0-9]+)+)(?![\w("'])/g;
// The Explorer lists the API in this order. `names` takes single types or global functions out of their file's group.
const GROUPS = [
  { id: 'game', title: 'game', file: 'game.lua', text: 'The game tree, Instances, players, creatures and outlines.' },
  { id: 'character', title: 'Characters', file: 'character.lua', text: 'game.Me for your own character, its signals, and the fields of every character.' },
  { id: 'stats', title: 'Stats', file: 'stats.lua', text: 'The numbers the game keeps for a character, and the modifiers that are on it.' },
  { id: 'items', title: 'Items', file: 'items.lua', text: 'game.Items, inventories and what a character carries.' },
  { id: 'session', title: 'Session', file: 'session.lua', text: 'game.Time, game.Weather, game.Prospect and the players of the session.' },
  { id: 'creature', title: 'Creatures', file: 'creature.lua', text: 'The fields of a creature, spawning one, and what the tables of the game say about a kind.' },
  { id: 'creature-models', title: 'Models', file: 'creature_models.lua', text: 'What game.Creatures:GetModel gives for the 3D model control.' },
  { id: 'data', title: 'Tables', file: 'data.lua', text: 'game.Data: the tables of the game, read as plain Lua and changed for as long as a mod is loaded.' },
  { id: 'recipes', title: 'Recipes', file: 'recipes.lua', text: 'game.Recipes: finding crafting recipes and changing what they take, give and where they are made.' },
  { id: 'workshop', title: 'Store', file: 'workshop.lua', text: 'game.Workshop: the store on the station, its categories, nodes and prices.' },
  { id: 'assets', title: 'Assets', file: 'assets.lua', text: 'game.Assets: assets of the game by path, materials of your own and shapes made of numbers.' },
  { id: 'blueprints', title: 'Blueprints', file: 'blueprints.lua', text: 'game.Blueprints: things described in Lua and spawned, and their parts.' },
  { id: 'ui', title: 'ui', file: 'ui.lua', text: 'The menu, windows, overlays, notifications, tags, hotkeys and themes.' },
  { id: 'controls', title: 'Controls', file: 'controls.lua', text: 'What goes in a window: text, buttons, switches, sliders, lists and grids.' },
  { id: 'task', title: 'task', file: 'task.lua', text: 'Run code alongside the game: wait, delay and repeat.' },
  { id: 'signal', title: 'Signal', names: ['WaxSignalLibrary', 'WaxSignal', 'WaxConnection', 'WaxFrameSignal'], text: 'Events, the functions connected to them, and game.Frame for every frame.' },
  { id: 'storage', title: 'storage', names: ['WaxStorage', 'persist'], text: 'Keep values when the mod reloads and when the game restarts.' },
  { id: 'mod', title: 'mod', file: 'mod.lua', text: 'What a mod knows about itself, require, and the functions that are blocked.' },
  { id: 'log', title: 'log', names: ['WaxLogger', 'WaxLogEntry', 'print'], text: 'Write to the Wax log.' },
];
// The guide page that explains a type, by type name. The first match wins.
const GUIDES = [
  [/^Wax(Game|Players)$/, '/docs/game'],
  [/^WaxInstance$/, '/docs/instances'],
  [/^WaxCreatureModel$/, '/docs/gui/model'],
  [/^Wax(Creature|Spawn)/, '/docs/creatures'],
  [/^Wax(Me|Character|PlayerCharacter)$/, '/docs/character'],
  [/^Wax(Damage|Death)Info$/, '/docs/events'],
  [/^Wax(CharacterStats|Modifier)$/, '/docs/stats'],
  [/^Wax(Item|Inventory|PlayerItems)/, '/docs/items'],
  [/^Wax(Time|Weather|Prospect|Player$)/, '/docs/time-and-weather'],
  [/^Wax(Data|RowHandle)/, '/docs/tables'],
  [/^WaxRecipe/, '/docs/recipes'],
  [/^Wax(Workshop|Store)/, '/docs/store'],
  [/^Wax(Assets|Mesh|Material|AssetColor)/, '/docs/assets'],
  [/^Wax(Blueprint|Thing|Part)/, '/docs/blueprints'],
  [/^WaxModel/, '/docs/gui/model'],
  [/^WaxFrameSignal$/, '/docs/watching'],
  [/^WaxHighlight/, '/docs/outlines'],
  [/^WaxUI$/, '/docs/menu'],
  [/^Wax(Window|Page|Status)/, '/docs/gui/windows'],
  [/^WaxOverlay/, '/docs/gui/overlays'],
  [/^WaxNotif/, '/docs/gui/notifications'],
  [/^WaxIcons$/, '/docs/gui/icons'],
  [/^WaxDebugPanel$/, '/docs/debug-panel'],
  [/^WaxTag/, '/docs/gui/tags'],
  [/^WaxHotkey/, '/docs/gui/hotkeys'],
  [/^Wax(Theme|Color$|Shape$)/, '/docs/gui/themes'],
  [/^WaxGrid/, '/docs/gui/grid'],
  [/^WaxTask$/, '/docs/tasks'],
  [/^Wax(Signal|Connection)/, '/docs/signals'],
  [/^WaxStorage$/, '/docs/storage'],
  [/^WaxLog/, '/docs/logging'],
  [/^Wax(ModInfo|Manifest|File)$/, '/docs/mods'],
];
const FILE_GUIDES = { 'controls.lua': '/docs/gui/controls' };
// Functions explained on another page than their type, by Explorer id.
const MEMBER_GUIDES = [
  [/^ui\.Windows?$/, '/docs/gui/windows'],
  [/^ui\.Overlay$/, '/docs/gui/overlays'],
  [/^ui\.Notify$/, '/docs/gui/notifications'],
  [/^ui\.Tag$/, '/docs/gui/tags'],
  [/^ui\.Hotkey$/, '/docs/gui/hotkeys'],
  [/^ui\.(\w*Theme\w*|Color|\w+Scale|AddSettings)$/, '/docs/gui/themes'],
  [/^WaxContainer\.Grid$/, '/docs/gui/grid'],
  [/^WaxContainer\.Model$/, '/docs/gui/model'],
  [/^WaxInstance\.GetPropertyChangedSignal$|^task\.every$/, '/docs/watching'],
  [/^ui\.(TextWidth|Shorten)$/, '/docs/gui/controls'],
  [/^WaxInstance\.(\w*Attribute\w*|\w+Tags?)$|^game\.GetTagged$/, '/docs/tags-and-attributes'],
  [/^print$/, '/docs/logging'],
  [/^persist$/, '/docs/storage'],
  [/^(require|raw)$/, '/docs/mods'],
];
// How an example gets the thing a method is called on, where the first function that returns one is a poor choice.
const SETUP = {
  WaxInstance: { subject: 'instance', lines: ['local instance = game.World'] },
  WaxContainer: { subject: 'window', lines: ['local window = ui.Window({ title = "Example" })'] },
  WaxWindow: { subject: 'window', lines: ['local window = ui.Window({ title = "Example" })'] },
  WaxConnection: { subject: 'connection', lines: ['local connection = game.MapChanged:Connect(function(name) end)'] },
  WaxControl: { subject: 'control', lines: ['local window = ui.Window({ title = "Example" })', 'local control = window:Toggle("Example")'] },
  WaxFrameSignal: { subject: 'frame', lines: ['local frame = game.Frame'] },
  WaxCharacter: { subject: 'character', lines: ['local character = game.Character'] },
  WaxPlayerCharacter: { subject: 'character', lines: ['local character = game.Character'] },
  WaxCharacterStats: { subject: 'character', lines: ['local character = game.Character'] },
  WaxTime: { subject: 'time', lines: ['local time = game.Time'] },
  WaxWeather: { subject: 'weather', lines: ['local weather = game.Weather'] },
  WaxProspect: { subject: 'prospect', lines: ['local prospect = game.Prospect'] },
  WaxPlayer: { subject: 'player', lines: ['local player = game.Players:GetPlayers()[1]'] },
  WaxItems: { subject: 'items', lines: ['local items = game.Items'] },
  WaxInventory: { subject: 'backpack', lines: ['local backpack = game.Me.Backpack'] },
  WaxPlayerItems: { subject: 'me', lines: ['local me = game.Me'] },
  WaxCreatureMembers: { subject: 'creature', lines: ['local creature = game.Creatures:GetNearest()'] },
};

if (!fs.existsSync(TYPES)) {
  console.log(`[generate-api] ${path.relative(DOCS, TYPES)} not found: keeping the reference pages that are already here.`);
  process.exit(0);
}

const notes = [];
const note = (file, line, text) => notes.push(`${file}:${line}: ${text}`);
const bare = [];

// ---------------------------------------------------------------------------------------------
// Reading types such as `fun(self: WaxSignal<F>, fn: F): WaxConnection` or `"a"|"b"|string`.

const CLOSER = { '(': ')', '{': '}', '[': ']', '<': '>' };

function skipSpaces(text, at) {
  while (at < text.length && (text[at] === ' ' || text[at] === '\t')) at++;
  return at;
}

function closeQuote(text, at) {
  const quote = text[at];
  let i = at + 1;
  while (i < text.length && text[i] !== quote) i += text[i] === '\\' ? 2 : 1;
  return Math.min(i + 1, text.length);
}

function closeBracket(text, at) {
  const stack = [CLOSER[text[at]]];
  let i = at + 1;
  while (i < text.length && stack.length) {
    const c = text[i];
    if (c === '"' || c === "'") {
      i = closeQuote(text, i);
      continue;
    }
    if (c === stack[stack.length - 1]) stack.pop();
    else if (CLOSER[c] && !(c === '<' && !/[\w>]/.test(text[i - 1] ?? ''))) stack.push(CLOSER[c]);
    i++;
  }
  return i;
}

function readMember(text, at) {
  let i = at;
  if (text.startsWith('...', i)) {
    i += 3;
    return i < text.length && /[\w"'({[]/.test(text[i]) ? readMember(text, i) : i;
  }
  const c = text[i];
  if (c === '"' || c === "'") i = closeQuote(text, i);
  else if (c === '`') i = text.indexOf('`', i + 1) === -1 ? text.length : text.indexOf('`', i + 1) + 1;
  else if (c === '{' || c === '(' || c === '[') i = closeBracket(text, i);
  else if (text.startsWith('fun(', i)) {
    i = closeBracket(text, i + 3);
    const colon = skipSpaces(text, i);
    if (text[colon] === ':') {
      i = readType(text, skipSpaces(text, colon + 1));
      while (text[i] === ',') i = readType(text, skipSpaces(text, i + 1));
    }
  } else {
    const word = /^[A-Za-z_][\w.]*/.exec(text.slice(i));
    if (!word) return at;
    i += word[0].length;
    if (text[i] === '<') i = closeBracket(text, i);
  }
  for (;;) {
    if (text.startsWith('[]', i)) i += 2;
    else if (text[i] === '?') i += 1;
    else break;
  }
  return i;
}

// Returns the index just past the type that starts at `at` (equal to `at` when there is none).
function readType(text, at) {
  let i = readMember(text, at);
  if (i === at) return at;
  for (;;) {
    const bar = skipSpaces(text, i);
    if (text[bar] !== '|') return i;
    const next = readMember(text, skipSpaces(text, bar + 1));
    if (next === skipSpaces(text, bar + 1)) return i;
    i = next;
  }
}

function splitTopLevel(text, separator) {
  const parts = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (c === '"' || c === "'") {
      i = closeQuote(text, i) - 1;
      continue;
    }
    if (CLOSER[c] && !(c === '<' && !/[\w>]/.test(text[i - 1] ?? ''))) depth++;
    else if (c === ')' || c === '}' || c === ']' || (c === '>' && depth > 0 && text[i - 1] !== '-')) depth--;
    else if (c === separator && depth === 0) {
      parts.push(text.slice(start, i).trim());
      start = i + 1;
    }
  }
  parts.push(text.slice(start).trim());
  return parts.filter((part) => part !== '');
}

// ---------------------------------------------------------------------------------------------
// Parsing one type file.

function parseFile(file, source) {
  const model = { file, classes: [], aliases: [], functions: [], values: [], tables: new Map() };
  const lines = source.split(/\r?\n/);
  let block = null;

  const newBlock = () => ({
    text: [],
    classes: [],
    aliases: [],
    alias: null,
    params: [],
    returns: [],
    generics: [],
    captured: [],
    overloads: [],
    type: null,
    deprecated: false,
    hasFunctionTags: false,
  });
  const takeText = () => {
    const text = block.text.join(' ').replace(/\s+/g, ' ').trim();
    block.text = [];
    return text;
  };

  function tag(name, rest, line) {
    switch (name) {
      case 'class': {
        const match = /^([\w.]+)\s*(<[^>]*>)?\s*(?::\s*(.+))?$/.exec(rest);
        if (!match) return note(file, line, `could not read @class "${rest}"`);
        const entry = {
          name: match[1],
          generics: match[2] ? match[2].slice(1, -1).split(',').map((part) => part.trim()) : [],
          parents: match[3] ? splitTopLevel(match[3], ',').filter((parent) => parent !== 'table') : [],
          description: takeText(),
          fields: [],
          methods: [],
          bound: null,
          file,
          line,
        };
        block.classes.push(entry);
        block.alias = null;
        return;
      }
      case 'field': {
        const owner = block.classes[block.classes.length - 1];
        if (!owner) return note(file, line, '@field outside a class');
        let text = rest.replace(/^(public|private|protected|package)\s+/, '');
        let fieldName;
        if (text[0] === '[') {
          const end = closeBracket(text, 0);
          fieldName = text.slice(0, end);
          text = text.slice(end);
        } else {
          const match = /^(\S+)/.exec(text);
          fieldName = match ? match[1] : '';
          text = text.slice(fieldName.length);
        }
        const optional = fieldName.endsWith('?');
        if (optional) fieldName = fieldName.slice(0, -1);
        const start = skipSpaces(text, 0);
        const end = readType(text, start);
        if (!fieldName || end === start) return note(file, line, `could not read @field "${rest}"`);
        owner.fields.push({
          name: fieldName,
          optional,
          type: text.slice(start, end),
          description: text.slice(end).trim(),
          line,
        });
        return;
      }
      case 'param': {
        const match = /^(\.\.\.|[\w]+)(\?)?\s+/.exec(rest);
        if (!match) return note(file, line, `could not read @param "${rest}"`);
        const start = match[0].length;
        const end = readType(rest, start);
        if (end === start) return note(file, line, `@param ${match[1]} has no type`);
        // A type in backticks is a class name given as text, which the editor reads as the generic of that name.
        const captured = /^`(\w+)`$/.exec(rest.slice(start, end));
        if (captured) block.captured.push(captured[1]);
        block.params.push({
          name: match[1],
          optional: Boolean(match[2]),
          type: captured ? 'string' : rest.slice(start, end),
          description: rest.slice(end).trim() || (captured ? 'The name of a class, given as text.' : ''),
        });
        block.hasFunctionTags = true;
        return;
      }
      case 'return': {
        let end = readType(rest, 0);
        if (end === 0) return note(file, line, `could not read @return "${rest}"`);
        // One line may name several values: `---@return WaxInstance?, number?`.
        const first = rest.slice(0, end);
        const more = [];
        for (;;) {
          const comma = skipSpaces(rest, end);
          if (rest[comma] !== ',') break;
          const start = skipSpaces(rest, comma + 1);
          const next = readType(rest, start);
          if (next === start) break;
          more.push(rest.slice(start, next));
          end = next;
        }
        let tail = rest.slice(end).trim();
        let returnName = '';
        // LuaLS reads the first word as the value's name; a capitalised word is taken as prose instead.
        const word = /^([a-z_]\w*)(?:\s+|$)/.exec(tail);
        if (tail.startsWith('#')) tail = tail.slice(1).trim();
        else if (word) {
          returnName = word[1];
          tail = tail.slice(word[0].length).replace(/^#\s*/, '').trim();
        }
        block.returns.push({ type: first, name: returnName, description: tail });
        for (const type of more) block.returns.push({ type, name: '', description: '' });
        block.hasFunctionTags = true;
        return;
      }
      case 'alias': {
        const match = /^([\w.]+)\s*(.*)$/.exec(rest);
        if (!match) return note(file, line, `could not read @alias "${rest}"`);
        const entry = { name: match[1], type: match[2].trim(), members: [], description: takeText(), file, line };
        if (entry.type) {
          const end = readType(entry.type, 0);
          if (end !== entry.type.length) note(file, line, `@alias ${entry.name}: text after the type was dropped ("${entry.type.slice(end).trim()}")`);
          entry.type = entry.type.slice(0, end);
        }
        block.aliases.push(entry);
        block.alias = entry;
        return;
      }
      case 'generic':
        for (const part of splitTopLevel(rest, ',')) block.generics.push(part);
        block.hasFunctionTags = true;
        return;
      case 'overload':
        block.overloads.push(rest.trim());
        block.hasFunctionTags = true;
        return;
      case 'type':
        block.type = rest.trim();
        return;
      case 'deprecated':
        block.deprecated = true;
        return;
      default:
        if (!IGNORED_TAGS.has(name)) note(file, line, `@${name} is not handled and was left out`);
    }
  }

  function flush(codeLine, line) {
    if (!block) return;
    const current = block;
    block = null;
    for (const entry of current.classes) model.classes.push(entry);
    for (const entry of current.aliases) model.aliases.push(entry);
    const text = current.text.join(' ').replace(/\s+/g, ' ').trim();

    const fn = /^(?:local\s+)?function\s+([\w.:]+)\s*\(([^)]*)\)/.exec(codeLine);
    if (fn) {
      const full = fn[1];
      const cut = Math.max(full.lastIndexOf('.'), full.lastIndexOf(':'));
      const args = fn[2].split(',').map((part) => part.trim()).filter(Boolean);
      const known = new Map(current.params.map((param) => [param.name, param]));
      for (const arg of args) {
        if (!known.has(arg)) note(file, line, `${full}: parameter "${arg}" has no @param`);
      }
      for (const param of current.params) {
        if (!args.includes(param.name)) note(file, line, `${full}: @param "${param.name}" is not in the function's argument list`);
      }
      if (!text && !current.deprecated) bare.push(full);
      // The page shows the widest type such a generic can be: `T : WaxInstance` reads as WaxInstance.
      current.generics = current.generics.filter((generic) => {
        const [name, base] = generic.split(':').map((part) => part.trim());
        if (!base || !current.captured.includes(name)) return true;
        const word = new RegExp(`\\b${name}\\b`, 'g');
        for (const value of current.returns) {
          if (!word.test(value.type)) continue;
          value.type = value.type.replace(word, base);
          const said = value.type.endsWith('[]') ? 'Instances of that class.' : value.type.endsWith('?') ? 'An Instance of that class, or nil.' : 'An Instance of that class.';
          value.description ||= said;
        }
        return false;
      });
      model.functions.push({
        table: cut === -1 ? null : full.slice(0, cut),
        separator: cut === -1 ? '' : full[cut],
        name: cut === -1 ? full : full.slice(cut + 1),
        args,
        params: known,
        returns: current.returns,
        generics: current.generics,
        overloads: current.overloads,
        deprecated: current.deprecated,
        description: text,
        file,
        line,
      });
      return;
    }

    const assignment = /^(local\s+)?([A-Za-z_]\w*)\s*=\s*(.+?)\s*$/.exec(codeLine);
    if (assignment) {
      const variable = assignment[2];
      const isTable = /^\{\s*\}$/.test(assignment[3]);
      const owner = current.classes[current.classes.length - 1];
      if (owner && isTable) {
        owner.bound = { name: variable, global: !assignment[1] };
        model.tables.set(variable, owner.name);
        if (text) note(file, line, `text between @class ${owner.name} and "${variable} = {}" was dropped`);
      } else if (!assignment[1]) {
        model.values.push({ name: variable, type: current.type ?? 'any', description: text, file, line });
      }
      if (current.hasFunctionTags) note(file, line, `@param/@return/@generic/@overload above "${variable}" do not belong to a function and were dropped`);
      return;
    }

    if (current.hasFunctionTags) note(file, line, 'annotations for a function are not followed by one and were dropped');
    if (text && current.classes.length === 0 && current.aliases.length === 0) {
      note(file, line, `a comment that documents nothing was dropped ("${text.slice(0, 50)}")`);
    }
    if (codeLine.trim() !== '' && !codeLine.trim().startsWith('--')) note(file, line, `this line was not understood: ${codeLine.trim().slice(0, 60)}`);
  }

  lines.forEach((raw, index) => {
    const line = index + 1;
    if (raw.startsWith('---')) {
      block ??= newBlock();
      const body = raw.slice(3);
      if (body.startsWith('@')) {
        const match = /^@(\w+)\s*(.*)$/.exec(body);
        if (match) tag(match[1], match[2].trim(), line);
        else note(file, line, `could not read "${body}"`);
      } else if (body.startsWith('|')) {
        if (!block.alias) return note(file, line, 'a "---|" line outside an @alias');
        const match = /^\|[>+]?\s*(.+?)(?:\s+#\s*(.*))?$/.exec(body);
        if (match) block.alias.members.push({ value: match[1].trim(), description: (match[2] ?? '').trim() });
      } else {
        block.text.push(body.trim());
      }
      return;
    }
    if (block) flush(raw, line);
    else if (raw.trim() !== '' && !raw.trim().startsWith('--')) {
      // A line with no annotations above it: still record what it declares.
      block = newBlock();
      flush(raw, line);
    }
  });
  if (block) flush('', lines.length);

  for (const fn of model.functions) {
    if (fn.table === null) continue;
    const owner = model.classes.find((entry) => entry.name === model.tables.get(fn.table));
    if (owner) owner.methods.push(fn);
    else note(file, fn.line, `${fn.table}${fn.separator}${fn.name}: "${fn.table}" is not a table declared after a @class`);
  }
  model.functions = model.functions.filter((fn) => fn.table === null);
  return model;
}

// ---------------------------------------------------------------------------------------------
// Working out how each thing is reached from a mod, and where it is documented.

const lowerFirst = (text) => text.charAt(0).toLowerCase() + text.slice(1);
const anchorOf = (text) => text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const isSignal = (type) => /^WaxSignal\b/.test(type);
const selfMethod = (field) => /^fun\(\s*self\b/.test(field.type);
// What the Explorer calls a type and a member: "ui", "ui.Notify", "WaxWindow.SetTitle", "print".
const typeId = (entry) => entry.path ?? entry.name;
const memberId = (fn) => (fn.deprecated || !fn.owner ? fn.name : `${typeId(fn.owner)}.${fn.name}`);
const inExplorer = (id) => `<InExplorer id=${JSON.stringify(id)} />`;

function resolve(models) {
  const classes = new Map();
  for (const model of models) for (const entry of model.classes) classes.set(entry.name, entry);

  // A table bound to a global is reached by that name; a class that is a field of one, through it.
  for (const entry of classes.values()) {
    if (entry.bound?.global) entry.path = entry.bound.name;
  }
  // Only when exactly one such field has that type: `game.World` is one of many Instances, not "the" Instance.
  const reached = new Map();
  for (const owner of classes.values()) {
    if (!owner.bound?.global) continue;
    for (const field of owner.fields) {
      if (!classes.has(field.type)) continue;
      reached.set(field.type, [...(reached.get(field.type) ?? []), `${owner.path}.${field.name}`]);
    }
  }
  for (const [name, paths] of reached) {
    const target = classes.get(name);
    if (paths.length === 1 && !target.path) target.path = paths[0];
  }

  const isObject = (entry, seen = new Set()) => {
    if (seen.has(entry.name)) return false;
    seen.add(entry.name);
    if (entry.methods.length > 0 || entry.bound) return true;
    if (entry.fields.some((field) => isSignal(field.type) || selfMethod(field))) return true;
    return entry.parents.some((parent) => classes.has(parent) && isObject(classes.get(parent), seen));
  };

  for (const entry of classes.values()) {
    entry.kind = entry.path ? 'namespace' : isObject(entry) ? 'object' : 'data';
    if (!entry.description && !/(Options|Settings)$/.test(entry.name)) bare.push(entry.name);
    entry.heading = entry.path ?? entry.name;
    entry.anchor = anchorOf(entry.path ?? entry.name);
    entry.subject = entry.path ?? lowerFirst(entry.bound?.name ?? entry.name.replace(/^Wax/, ''));
    // Fields written as `fun(self: ...)` are methods.
    for (const field of entry.fields.filter(selfMethod)) {
      const open = field.type.indexOf('(');
      const close = closeBracket(field.type, open);
      const inner = splitTopLevel(field.type.slice(open + 1, close - 1), ',').slice(1);
      const args = [];
      const params = new Map();
      for (const part of inner) {
        const match = /^(\.\.\.|\w+)(\?)?\s*:\s*(.+)$/.exec(part);
        const argName = match ? match[1] : part;
        args.push(argName);
        params.set(argName, { name: argName, optional: Boolean(match?.[2]), type: match ? match[3] : 'any', description: '' });
      }
      const after = field.type.slice(close).replace(/^\s*:\s*/, '').trim();
      entry.methods.push({
        table: entry.name,
        separator: ':',
        name: field.name,
        args,
        params,
        returns: after ? splitTopLevel(after, ',').map((type) => ({ type, name: '', description: '' })) : [],
        generics: [],
        overloads: [],
        deprecated: false,
        description: field.description,
        file: entry.file,
        line: field.line,
      });
    }
    entry.fields = entry.fields.filter((field) => !selfMethod(field));
    for (const fn of entry.methods) {
      fn.owner = entry;
      fn.display = `${entry.subject}${fn.separator}${fn.name}`;
    }
  }
  return classes;
}

// ---------------------------------------------------------------------------------------------
// What is newer than the released Wax.

// Sets `next` on every class, field, signal, function, parameter, value and named value that the released type
// files do not have. A file the release does not have at all makes a page that is new as a whole (`model.next`).
// Returns false, and marks nothing, when the released files are not there.
function markNewer(models) {
  const listed = fs.existsSync(RELEASED_TYPES)
    ? fs.readdirSync(RELEASED_TYPES, { withFileTypes: true }).filter((entry) => entry.isFile() && entry.name.endsWith('.lua') && !SKIP.has(entry.name))
    : [];
  if (listed.length === 0) return false;
  // Reading the old files must not add to what is reported about the new ones.
  const [notesBefore, bareBefore] = [notes.length, bare.length];
  const old = listed.map((entry) => parseFile(entry.name, fs.readFileSync(path.join(RELEASED_TYPES, entry.name), 'utf8')));
  const oldClasses = resolve(old);
  notes.length = notesBefore;
  bare.length = bareBefore;

  const oldFiles = new Set(old.map((model) => model.file));
  const oldFunctions = new Map(old.flatMap((model) => model.functions.map((fn) => [fn.name, fn])));
  const oldValues = new Set(old.flatMap((model) => model.values.map((value) => value.name)));
  const oldAliases = new Map(old.flatMap((model) => model.aliases.map((entry) => [entry.name, entry])));
  const valuesOf = (entry) => new Set(entry.members.length ? entry.members.map((member) => member.value) : splitTopLevel(entry.type, '|'));
  const markParams = (fn, before) => {
    for (const [name, param] of fn.params) if (!before.params.has(name)) param.next = true;
  };

  for (const model of models) {
    model.next = !oldFiles.has(model.file);
    for (const entry of model.classes) {
      const before = oldClasses.get(entry.name);
      if (!before) {
        entry.next = true;
        continue;
      }
      const fields = new Set(before.fields.map((field) => field.name));
      const methods = new Map(before.methods.map((fn) => [fn.name, fn]));
      for (const field of entry.fields) if (!fields.has(field.name) && !methods.has(field.name)) field.next = true;
      for (const fn of entry.methods) {
        if (!methods.has(fn.name)) fn.next = !fields.has(fn.name);
        else markParams(fn, methods.get(fn.name));
      }
    }
    for (const fn of model.functions) {
      if (!oldFunctions.has(fn.name)) fn.next = true;
      else markParams(fn, oldFunctions.get(fn.name));
    }
    for (const value of model.values) if (!oldValues.has(value.name)) value.next = true;
    for (const entry of model.aliases) {
      const before = oldAliases.get(entry.name);
      if (!before) {
        entry.next = true;
        continue;
      }
      const values = valuesOf(before);
      for (const member of entry.members) if (!values.has(member.value)) member.next = true;
    }
  }
  return true;
}

// ---------------------------------------------------------------------------------------------
// Writing MDX.

function escapeText(text, inTable) {
  // Outside `code`, the characters MDX would read as JSX or an expression are escaped.
  return text
    .split(/(`[^`]*`)/)
    .map((part, index) => {
      let out = index % 2 === 1 ? part : part.replace(/[{}<]/g, (c) => `\\${c}`);
      if (inTable) out = out.replace(/\|/g, '\\|');
      return out;
    })
    .join('');
}

function build(models) {
  const classes = resolve(models);
  const compared = markNewer(models);
  const pageOf = new Map();
  for (const model of models) {
    const config = PAGES[model.file] ?? {
      slug: anchorOf(path.basename(model.file, '.lua')),
      title: path.basename(model.file, '.lua'),
      description: `What ${model.file} defines.`,
    };
    model.config = config;
    for (const entry of model.classes) pageOf.set(entry.name, config.slug);
    for (const entry of model.aliases) pageOf.set(entry.name, config.slug);
  }

  const aliases = new Map();
  for (const model of models) for (const entry of model.aliases) aliases.set(entry.name, entry);
  const targetOf = (name) => {
    if (classes.has(name)) return `${ROUTE}/${pageOf.get(name)}#${classes.get(name).anchor}`;
    if (aliases.has(name)) return `${ROUTE}/${pageOf.get(name)}#${anchorOf(name)}`;
    if (gameTypes.has(name)) return `/explorer?game=${encodeURIComponent(name)}`;
    return null;
  };

  // Every function by the names prose uses for it: "ui.Notify", "Window:StatusBar", "game:GetTagged".
  const spoken = new Map();
  const allFunctions = [];
  for (const model of models) {
    for (const fn of model.functions) {
      fn.display = fn.name;
      fn.anchor = anchorOf(fn.name);
      fn.page = model.config.slug;
      allFunctions.push(fn);
    }
    for (const entry of model.classes) {
      for (const fn of entry.methods) {
        fn.anchor = anchorOf(fn.display);
        fn.page = model.config.slug;
        allFunctions.push(fn);
        const href = `${ROUTE}/${fn.page}#${fn.anchor}`;
        if (entry.path) spoken.set(fn.display, href);
        if (entry.bound && !entry.path) spoken.set(`${entry.bound.name}${fn.separator}${fn.name}`, href);
      }
    }
  }
  const spokenPattern = spoken.size
    ? new RegExp(
        `(?<![\\w.:])(${[...spoken.keys()].sort((a, b) => b.length - a.length).map((key) => key.replace(/[.]/g, '\\.')).join('|')})(\\([^()\\s]*\\)(?:\\.\\w+)*)?(?![\\w(])`,
        'g',
      )
    : null;

  // Names Wax itself uses. `game.GameState` is a member of game, not the engine class of the same name.
  const ownNames = new Set([...classes.keys(), ...aliases.keys()]);
  for (const entry of classes.values()) for (const item of [...entry.fields, ...entry.methods]) ownNames.add(item.name);

  const prose = (text, inTable, selfHref) => {
    if (!text) return '';
    const linked = text
      .split(/(`[^`]*`)/)
      .map((part, index) => {
        if (index % 2 === 1) return part;
        // A class of the game named in a sentence links to its entry in the Explorer.
        const named = part.replace(GAME_WORD, (word) =>
          gameTypes.has(word) && !ownNames.has(word) ? `[\`${word}\`](/explorer?game=${encodeURIComponent(word)})` : word,
        );
        if (!spokenPattern) return named;
        return named.replace(spokenPattern, (whole, name) => {
          const href = spoken.get(name);
          return href === selfHref ? `\`${whole}\`` : `[\`${whole}\`](${href})`;
        });
      })
      .join('');
    return escapeText(linked, inTable);
  };

  const code = (text, inTable) => `\`${inTable ? text.replace(/\|/g, '\\|') : text}\``;
  // A type for a table cell or a sentence: each member of a union on its own, linked when it is documented.
  const typeLinks = (type, inTable) =>
    splitTopLevel(type, '|')
      .map((member) => {
        const match = /^([\w.]+)((?:\[\]|\?)*)$/.exec(member);
        const href = match && targetOf(match[1]);
        return href ? `[${code(member, inTable)}](${href})` : code(member, inTable);
      })
      .join(inTable ? ' \\| ' : ' | ');

  // A table; its last column is left out when every row leaves it empty.
  const table = (out, headers, rows) => {
    if (!rows.length) return;
    const last = headers.length - 1;
    const keep = rows.some((row) => row[last] !== '') ? headers.length : last;
    out.push(`| ${headers.slice(0, keep).join(' | ')} |`, `| ${headers.slice(0, keep).map(() => '---').join(' | ')} |`);
    for (const row of rows) out.push(`| ${row.slice(0, keep).join(' | ')} |`);
    out.push('');
  };
  // A member with no text of its own is described by the class it holds.
  const fieldText = (field) => field.description || classes.get(field.type)?.description || '';

  const mentions = (type, name) => new RegExp(`(?<![\\w.])${name}(?![\\w.])`).test(type);
  const fnLink = (fn) => `[\`${fn.display}\`](${ROUTE}/${fn.page}#${fn.anchor})`;

  // The mark for one newer entry. None on a page that is new as a whole, and none inside a class that is marked itself.
  let marking = { page: false, inside: false, written: 0 };
  const marked = (item) => {
    if (!item?.next || marking.page || marking.inside) return false;
    marking.written++;
    return true;
  };
  const mark = (item) => (marked(item) ? ` ${NEXT_MARK}` : '');

  function writeFunction(out, fn, level, used) {
    const args = fn.args.map((arg) => `${arg}${fn.params.get(arg)?.optional ? '?' : ''}`);
    let anchor = fn.anchor;
    for (let n = 2; used.has(anchor); n++) anchor = `${fn.anchor}-${n}`;
    if (anchor !== fn.anchor) note(fn.file, fn.line, `${fn.display} shares its anchor with something else; it became #${anchor}`);
    used.add(anchor);
    fn.anchor = anchor;
    out.push(`${'#'.repeat(level)} \`${fn.display}(${args.join(', ')})\` [#${anchor}]`, '');
    if (marked(fn)) out.push(NEXT_MARK_LINE, '');
    if (fn.description) out.push(prose(fn.description, false, `${ROUTE}/${fn.page}#${anchor}`), '');

    const generics = fn.generics.length ? `<${fn.generics.join(', ')}>` : '';
    const typed = fn.args.map((arg) => {
      const param = fn.params.get(arg);
      return `${arg}${param?.optional ? '?' : ''}: ${param?.type ?? 'any'}`;
    });
    const result = fn.returns.length ? `: ${fn.returns.map((entry) => entry.type).join(', ')}` : '';
    out.push('```lua', `${fn.display}${generics}(${typed.join(', ')})${result}`);
    for (const overload of fn.overloads) {
      // On a method written with a colon, the overload's `self` is the object in front of the colon.
      const shape = overload.replace(/^fun/, '');
      out.push(`${fn.display}${fn.separator === ':' ? shape.replace(/^\(\s*self\s*:\s*[\w.<>]+\s*,?\s*/, '(') : shape}`);
    }
    out.push('```', '');

    table(
      out,
      ['Parameter', 'Type', 'Description'],
      fn.args.map((arg) => {
        const param = fn.params.get(arg);
        return [`${code(arg, true)}${param?.optional ? ' (optional)' : ''}${fn.next ? '' : mark(param)}`, typeLinks(param?.type ?? 'any', true), prose(param?.description ?? '', true)];
      }),
    );
    if (fn.returns.length === 1) {
      const entry = fn.returns[0];
      const detail = [entry.name ? `(${code(entry.name)})` : '', prose(entry.description)].filter(Boolean).join(' ');
      out.push(`**Returns** ${typeLinks(entry.type)}${detail ? ` ${detail}` : ''}`, '');
    } else if (fn.returns.length > 1) {
      out.push('**Returns**', '');
      for (const entry of fn.returns) {
        out.push(`- ${typeLinks(entry.type)}${entry.name ? ` (${code(entry.name)})` : ''}${entry.description ? ` ${prose(entry.description)}` : ''}`);
      }
      out.push('');
    } else {
      out.push('**Returns** nothing.', '');
    }
    out.push(inExplorer(memberId(fn)), '');
  }

  function writeFields(out, fields, heading) {
    table(
      out,
      [heading, 'Type', 'Description'],
      fields.map((field) => {
        const label = field.name.startsWith('[') ? `any other key (${code(field.name, true)})` : code(field.name, true);
        const required = heading === 'Option' && !field.optional && !field.name.startsWith('[') ? ' (required)' : '';
        const optional = heading !== 'Option' && field.optional ? ' (optional)' : '';
        return [`${label}${required}${optional}${mark(field)}`, typeLinks(field.type, true), prose(fieldText(field), true)];
      }),
    );
  }

  function writeClass(out, entry, used) {
    used.add(entry.anchor);
    out.push(`## ${entry.kind === 'namespace' ? `\`${entry.heading}\`` : entry.heading} [#${entry.anchor}]`, '');
    if (marked(entry)) out.push(NEXT_MARK_LINE, '');
    marking.inside = Boolean(entry.next);
    if (entry.description) out.push(prose(entry.description), '');

    const facts = [];
    if (entry.kind === 'namespace') facts.push(`Type name: ${code(entry.name)}.`);
    const parents = entry.parents.filter((parent) => parent !== 'WaxOptions');
    if (parents.length) {
      const list = parents.map((parent) => (targetOf(parent) ? `[${code(parent)}](${targetOf(parent)})` : code(parent))).join(', ');
      facts.push(entry.kind === 'data' ? `Extends ${list}.` : `It can also do everything ${list} can.`);
    }
    const listed = (functions) => `${functions.slice(0, 8).map(fnLink).join(', ')}${functions.length > 8 ? ' and others' : ''}`;
    if (entry.kind !== 'namespace') {
      const makers = allFunctions.filter((fn) => fn.owner !== entry && !fn.deprecated && fn.returns.some((value) => mentions(value.type, entry.name)));
      if (makers.length) facts.push(`${entry.kind === 'object' ? 'You get one from' : 'Returned by'} ${listed(makers)}.`);
    }
    if (entry.kind === 'object' && entry.methods.length) facts.push(`Below, ${code(entry.subject)} stands for one of these.`);
    if (entry.kind === 'data') {
      const users = allFunctions.filter((fn) => !fn.deprecated && [...fn.params.values()].some((param) => mentions(param.type, entry.name)));
      if (users.length) facts.push(`Used by ${listed(users)}.`);
    }
    if (facts.length) out.push(facts.join(' '), '');
    out.push(inExplorer(typeId(entry)), '');

    const signals = entry.fields.filter((field) => isSignal(field.type));
    const others = entry.fields.filter((field) => !isSignal(field.type));
    if (entry.kind === 'data') {
      const options = /(Options|Settings)$/.test(entry.name) || entry.parents.includes('WaxOptions');
      writeFields(out, others, options ? 'Option' : 'Field');
    } else {
      writeFields(out, others, entry.kind === 'namespace' ? 'Member' : 'Property');
    }
    table(
      out,
      ['Signal', 'Handler receives', 'Description'],
      signals.map((field) => {
        const shape = /^WaxSignal<fun\((.*)\)>$/.exec(field.type);
        const part = (text) => {
          const match = /^(\.\.\.|\w+)\??\s*:\s*(.+)$/.exec(text);
          return match ? `${code(match[1], true)}: ${typeLinks(match[2], true)}` : code(text, true);
        };
        const receives = !shape ? 'depends on the control' : shape[1].trim() === '' ? 'nothing' : splitTopLevel(shape[1], ',').map(part).join(', ');
        return [`${code(field.name, true)}${mark(field)}`, receives, prose(field.description, true)];
      }),
    );
    for (const fn of entry.methods.filter((method) => !method.deprecated)) writeFunction(out, fn, 3, used);
    marking.inside = false;
  }

  function writeAlias(out, entry, used) {
    used.add(anchorOf(entry.name));
    out.push(`### ${entry.name} [#${anchorOf(entry.name)}]`, '');
    if (marked(entry)) out.push(NEXT_MARK_LINE, '');
    if (entry.description) out.push(prose(entry.description), '');
    const members = entry.members.length
      ? entry.members
      : splitTopLevel(entry.type, '|').length > 1
        ? splitTopLevel(entry.type, '|').map((value) => ({ value, description: '' }))
        : [];
    if (members.length === 0) {
      out.push(`The same as ${typeLinks(entry.type)}.`, '');
    } else if (members.some((member) => member.description)) {
      table(out, ['Value', 'Description'], members.map((member) => [`${code(member.value, true)}${entry.next ? '' : mark(member)}`, prose(member.description, true)]));
    } else {
      const literal = members.filter((member) => /^["']/.test(member.value));
      const open = members.filter((member) => !/^["']/.test(member.value));
      const list = literal.map((member) => `${code(member.value)}${entry.next ? '' : mark(member)}`).join(', ');
      const rest = open.map((member) => typeLinks(member.value)).join(' or ');
      out.push(literal.length ? `One of ${list}${rest ? `, or any other ${rest}` : ''}.` : `One of ${rest}.`, '');
    }
    out.push(inExplorer(entry.name), '');
  }

  const files = new Map();
  let marks = 0;
  for (const model of models) {
    const config = model.config;
    const out = [
      '---',
      `title: ${JSON.stringify(config.title)}`,
      `description: ${JSON.stringify(config.description)}`,
      ...(config.icon ? [`icon: ${config.icon}`] : []),
      '---',
      '',
      `{/* ${MARKER} from wax/types/${model.file}. Do not edit: change the type file and run "npm run generate". */}`,
      '',
      ...(config.note || model.next ? [config.note ?? NEXT, ''] : []),
      'The [Explorer](/explorer) searches everything on this page, and the classes of the game too.',
      '',
    ];
    const legendAt = out.length;
    marking = { page: Boolean(model.next), inside: false, written: 0 };
    if (config.note === NEXT && compared && !model.next) note(model.file, 1, 'its page says everything on it is newer, and the released Wax has this file');
    const used = new Set();
    const lead = (config.lead ?? []).map((name) => model.classes.find((entry) => entry.name === name)).filter(Boolean);
    const rest = model.classes.filter((entry) => !lead.includes(entry));
    const ordered = [
      ...lead,
      ...rest.filter((entry) => entry.kind === 'namespace' && entry.bound?.global),
      ...rest.filter((entry) => entry.kind === 'namespace' && !entry.bound?.global),
    ];
    for (const entry of ordered) writeClass(out, entry, used);

    const live = model.functions.filter((fn) => !fn.deprecated);
    if (live.length) {
      out.push('## Global functions [#global-functions]', '', 'Call these by name, with nothing in front.', '');
      for (const fn of live) writeFunction(out, fn, 3, used);
    }
    if (model.values.length) {
      out.push('## Global values [#global-values]', '');
      for (const value of model.values) {
        used.add(anchorOf(value.name));
        out.push(`### \`${value.name}\` [#${anchorOf(value.name)}]`, '');
        if (marked(value)) out.push(NEXT_MARK_LINE, '');
        if (value.description) out.push(prose(value.description), '');
        out.push(`**Type** ${typeLinks(value.type)}`, '', inExplorer(value.name), '');
      }
    }

    for (const entry of rest.filter((item) => item.kind === 'object')) writeClass(out, entry, used);
    for (const entry of rest.filter((item) => item.kind === 'data')) writeClass(out, entry, used);

    if (model.aliases.length) {
      out.push('## Named values [#named-values]', '', 'Short names for a fixed set of values. Where a function asks for one of these, pass one of the values listed.', '');
      for (const entry of model.aliases) writeAlias(out, entry, used);
    }

    const blocked = [...model.functions, ...model.classes.flatMap((entry) => entry.methods)].filter((fn) => fn.deprecated);
    if (blocked.length) {
      out.push(`## ${config.deprecatedTitle ?? 'Deprecated'} [#${anchorOf(config.deprecatedTitle ?? 'Deprecated')}]`, '');
      if (config.deprecatedIntro) out.push(config.deprecatedIntro, '');
      table(out, ['Function', 'Note'], blocked.map((fn) => [code(fn.display, true), prose(fn.description, true)]));
      out.push(inExplorer(BLOCKED), '');
    }

    if (marking.written > 0) out.splice(legendAt, 0, NEXT_LEGEND, '');
    marks += marking.written;
    files.set(`${config.slug}.mdx`, out.join('\n'));
  }
  return { files, marks, compared, explorer: explorerData(models, classes, aliases, allFunctions, pageOf) };
}

// ---------------------------------------------------------------------------------------------
// The same model as JSON, for the Explorer page.

const GLOBALS = 'globals';
const BLOCKED = 'blocked';
const SAMPLES = new Map([
  ['string', '"text"'],
  ['number', '1'],
  ['integer', '1'],
  ['boolean', 'true'],
]);

function explorerData(models, classes, aliases, allFunctions, pageOf) {
  const live = allFunctions.filter((fn) => !fn.deprecated);
  const mentions = (type, name) => new RegExp(`(?<![\\w.])${name}(?![\\w.])`).test(type);
  const refOf = (entry) => `${ROUTE}/${pageOf.get(entry.name)}#${entry.anchor ?? anchorOf(entry.name)}`;
  const first = (rules, text) => rules.find(([pattern]) => pattern.test(text))?.[1];

  // A guide is only linked when its page is there. The link shows the page's own title.
  const guides = new Map();
  function guide(href) {
    if (!href) return undefined;
    if (!guides.has(href)) {
      const file = path.join(DOCS, 'content', `${href.replace(/^\//, '')}.mdx`);
      const title = fs.existsSync(file) ? /^title:\s*(.+)$/m.exec(fs.readFileSync(file, 'utf8'))?.[1] : null;
      if (!title) notes.push(`explorer: the guide ${href} has no page, so it is not linked`);
      guides.set(href, title ? { href, title: title.trim().replace(/^"(.*)"$/, '$1') } : undefined);
    }
    return guides.get(href);
  }
  const typeGuide = (entry) => guide(first(GUIDES, entry.name) ?? FILE_GUIDES[entry.file]);

  const groups = GROUPS.map((group) => ({ id: group.id, title: group.title, text: group.text, types: [], members: [] }));
  function groupOf(name, file) {
    const config = GROUPS.find((group) => group.names?.includes(name)) ?? GROUPS.find((group) => group.file === file);
    const id = config?.id ?? anchorOf(path.basename(file, '.lua'));
    let group = groups.find((entry) => entry.id === id);
    if (!group) groups.push((group = { id, title: path.basename(file, '.lua'), text: '', types: [], members: [] }));
    return group;
  }

  // What an example writes for one argument: a function is written out, anything else goes by its name.
  function argument(param, name) {
    const type = param?.type ?? '';
    if (!type.startsWith('fun(')) return name;
    const close = closeBracket(type, 3);
    const inner = splitTopLevel(type.slice(4, close - 1), ',').map((part) => /^(\.\.\.|\w+)/.exec(part)?.[1] ?? '_');
    return `function(${inner.join(', ')}) end`;
  }
  function callText(fn, subject, replace = {}) {
    const args = fn.args.map((arg) => replace[arg] ?? argument(fn.params.get(arg), arg));
    return `${fn.owner ? `${subject}${fn.separator}` : ''}${fn.name}(${args.join(', ')})`;
  }
  const exactly = (fn, name) => fn.returns.length > 0 && fn.returns[0].type.replace(/\?$/, '') === name;
  // The lines that make the thing a method is called on, and the name it then goes by.
  function setupFor(name, depth = 0) {
    if (SETUP[name]) return SETUP[name];
    const entry = classes.get(name);
    if (entry.path) return { subject: entry.path, lines: [] };
    if (depth < 2) {
      for (const fn of live) {
        if (!fn.owner || fn.owner === entry || !exactly(fn, name)) continue;
        const owner = setupFor(fn.owner.name, depth + 1);
        if (owner.subject === entry.subject) continue;
        return { subject: entry.subject, lines: [...owner.lines, `local ${entry.subject} = ${callText(fn, owner.subject)}`] };
      }
    }
    return { subject: entry.subject, lines: [] };
  }
  const declared = (lines) => lines.flatMap((line) => /^local ([\w, ]+) =/.exec(line)?.[1].split(/,\s*/) ?? []);
  function resultName(value) {
    if (value.name) return value.name;
    const type = value.type.replace(/\?$/, '');
    const base = type.replace(/\[\]$/, '').replace(/<.*$/, '');
    const entry = classes.get(base);
    if (!entry && !aliases.has(base)) return type.endsWith('[]') ? 'list' : 'result';
    const word = entry?.kind === 'object' ? entry.subject : lowerFirst(base.replace(/^Wax/, ''));
    return type.endsWith('[]') ? `${word}s` : word;
  }
  function callLines(fn, replace) {
    const setup = fn.owner ? setupFor(fn.owner.name) : { subject: '', lines: [] };
    const taken = new Set([setup.subject, ...declared(setup.lines), ...fn.args]);
    const names = fn.returns.map((value) => {
      let name = resultName(value);
      for (let n = 1; taken.has(name); n++) name = n === 1 ? 'result' : `result${n}`;
      taken.add(name);
      return name;
    });
    return { lines: [...setup.lines, `${names.length ? `local ${names.join(', ')} = ` : ''}${callText(fn, setup.subject, replace)}`], names };
  }
  const useOfFunction = (fn) => (fn.deprecated ? '' : callLines(fn).lines.join('\n'));

  const signalArgs = (type) => {
    const shape = /^WaxSignal<fun\((.*)\)>$/.exec(type);
    return shape ? splitTopLevel(shape[1], ',').map((part) => /^(\.\.\.|\w+)/.exec(part)?.[1] ?? '_') : ['...'];
  };
  function useOfSignal(entry, field, body) {
    const setup = setupFor(entry.name);
    const args = signalArgs(field.type);
    const inside = body ?? (args.length ? `print(${args.join(', ')})` : `print("${field.name}")`);
    return [...setup.lines, `${setup.subject}.${field.name}:Connect(function(${args.join(', ')})`, `    ${inside}`, 'end)'].join('\n');
  }

  // A value to write for an option, where its type leaves no doubt.
  function sample(type) {
    const plain = type.replace(/\?$/, '');
    if (plain.startsWith('fun(')) return argument({ type: plain }, 'value');
    const members = aliases.has(plain)
      ? aliases.get(plain).members.length
        ? aliases.get(plain).members.map((member) => member.value)
        : splitTopLevel(aliases.get(plain).type, '|')
      : splitTopLevel(plain, '|');
    if (members.length > 0 && members.every((member) => /^["']/.test(member) || member === 'string') && /^["']/.test(members[0])) return members[0];
    return SAMPLES.get(plain) ?? 'value';
  }
  const key = (name) => (/^[A-Za-z_]\w*$/.test(name) ? name : `[${JSON.stringify(name)}]`);
  function useOfField(entry, field) {
    if (field.name.startsWith('[')) return '';
    if (entry.kind !== 'data') {
      const setup = setupFor(entry.name);
      return [...setup.lines, `print(${setup.subject}.${field.name})`].join('\n');
    }
    const takes = (fn) => fn.args.find((arg) => mentions(fn.params.get(arg)?.type ?? '', entry.name));
    const user = live.find(takes);
    const maker = live.find((fn) => fn.owner !== entry && fn.returns.some((value) => mentions(value.type, entry.name)));
    const options = /(Options|Settings|Query)$/.test(entry.name) || entry.parents.includes('WaxOptions');
    if (user && (options || !maker)) return callLines(user, { [takes(user)]: `{ ${key(field.name)} = ${sample(field.type)} }` }).lines.join('\n');
    if (maker) {
      const at = maker.returns.findIndex((value) => mentions(value.type, entry.name));
      const made = callLines(maker);
      const one = maker.returns[at].type.replace(/\?$/, '').endsWith('[]') ? `${made.names[at]}[1]` : made.names[at];
      return [...made.lines, `print(${one}.${field.name})`].join('\n');
    }
    for (const owner of classes.values()) {
      const signal = owner.fields.find((item) => isSignal(item.type) && mentions(item.type, entry.name));
      if (!signal) continue;
      const shape = /^WaxSignal<fun\((.*)\)>$/.exec(signal.type);
      const part = splitTopLevel(shape?.[1] ?? '', ',').find((item) => mentions(item, entry.name));
      const name = /^\w+/.exec(part ?? '')?.[0];
      if (name) return useOfSignal(owner, signal, `print(${name}.${field.name})`);
    }
    return '';
  }

  // A type the definitions do not describe is described by the function it belongs to.
  function about(entry, makers, users) {
    const options = /(Options|Settings|Query)$/.test(entry.name) || entry.parents.includes('WaxOptions');
    if (entry.kind === 'data' && options && users.length) return `The options that ${users[0].display} takes.`;
    if (entry.kind !== 'namespace' && makers.length) return `What ${makers[0].display} gives back.`;
    return '';
  }

  const spoken = {};
  const drop = (object) => Object.fromEntries(Object.entries(object).filter(([, value]) => value !== undefined && value !== '' && value !== false && !(Array.isArray(value) && value.length === 0)));
  const paramOf = (fn) => (arg) => {
    const param = fn.params.get(arg);
    return drop({ name: arg, type: param?.type ?? 'any', optional: Boolean(param?.optional), text: param?.description ?? '', next: Boolean(param?.next && !fn.next && !fn.owner?.next) });
  };
  function functionRow(fn, ownerGuide) {
    const id = memberId(fn);
    const own = guide(first(MEMBER_GUIDES, id));
    const shape = (overload) => {
      const text = overload.replace(/^fun/, '');
      return `${fn.display}${fn.separator === ':' ? text.replace(/^\(\s*self\s*:\s*[\w.<>]+\s*,?\s*/, '(') : text}`;
    };
    return drop({
      id,
      name: fn.name,
      call: fn.display,
      params: fn.args.map(paramOf(fn)),
      returns: fn.returns.map((value) => drop({ type: value.type, name: value.name, text: value.description })),
      generics: fn.generics,
      overloads: fn.overloads.map(shape),
      text: fn.description,
      next: Boolean(fn.next || fn.owner?.next),
      ref: fn.deprecated ? undefined : `${ROUTE}/${fn.page}#${fn.anchor}`,
      guide: own && own.href !== ownerGuide?.href ? own : undefined,
      use: useOfFunction(fn),
    });
  }

  const types = [];
  for (const model of models) {
    for (const entry of model.classes) {
      const id = typeId(entry);
      const entryGuide = typeGuide(entry);
      const setup = entry.kind === 'object' ? setupFor(entry.name) : null;
      const makers = entry.kind === 'namespace' ? [] : live.filter((fn) => fn.owner !== entry && fn.returns.some((value) => mentions(value.type, entry.name)));
      const users = entry.kind === 'data' ? live.filter((fn) => [...fn.params.values()].some((param) => mentions(param.type, entry.name))) : [];
      const fieldRow = (field) =>
        drop({
          id: `${id}.${field.name}`,
          name: field.name,
          type: field.type,
          optional: field.optional,
          text: field.description || classes.get(field.type)?.description || '',
          next: Boolean(field.next || entry.next),
          use: useOfField(entry, field),
        });
      const methods = entry.methods.filter((fn) => !fn.deprecated);
      for (const fn of methods) {
        if (entry.path) spoken[fn.display] = memberId(fn);
        if (entry.bound && !entry.path) spoken[`${entry.bound.name}${fn.separator}${fn.name}`] = memberId(fn);
      }
      types.push(
        drop({
          id,
          name: entry.name,
          title: entry.heading,
          kind: entry.kind,
          group: groupOf(entry.name, entry.file).id,
          text: entry.description || about(entry, makers, users),
          next: entry.next,
          parents: entry.parents,
          generics: entry.generics,
          ref: refOf(entry),
          guide: entryGuide,
          makers: makers.map(memberId),
          users: users.map(memberId),
          use: setup && setup.lines.length ? setup.lines.join('\n') : '',
          props: entry.fields.filter((field) => !isSignal(field.type)).map(fieldRow),
          signals: entry.fields
            .filter((field) => isSignal(field.type))
            .map((field) => {
              const shape = /^WaxSignal<fun\((.*)\)>$/.exec(field.type);
              return drop({
                id: `${id}.${field.name}`,
                name: field.name,
                type: field.type,
                receives: shape ? shape[1].trim() : undefined,
                open: !shape,
                text: field.description,
                next: Boolean(field.next || entry.next),
                use: useOfSignal(entry, field),
              });
            }),
          funcs: methods.map((fn) => functionRow(fn, entryGuide)),
        }),
      );
      groupOf(entry.name, entry.file).types.push(id);
    }
    for (const entry of model.aliases) {
      const split = splitTopLevel(entry.type, '|');
      const values = entry.members.length ? entry.members : split.length > 1 ? split.map((value) => ({ value, description: '' })) : [];
      types.push(
        drop({
          id: entry.name,
          name: entry.name,
          title: entry.name,
          kind: 'alias',
          group: groupOf(entry.name, entry.file).id,
          text: entry.description,
          next: entry.next,
          ref: `${ROUTE}/${pageOf.get(entry.name)}#${anchorOf(entry.name)}`,
          guide: guide(first(GUIDES, entry.name) ?? FILE_GUIDES[entry.file]),
          type: entry.type,
          values: values.map((member) => drop({ value: member.value, text: member.description, next: Boolean(member.next && !entry.next) })),
        }),
      );
      groupOf(entry.name, entry.file).types.push(entry.name);
    }
  }

  const globals = models.flatMap((model) => model.functions.filter((fn) => !fn.deprecated));
  const values = models.flatMap((model) => model.values.map((value) => ({ ...value, page: model.config.slug })));
  const blocked = models.flatMap((model) =>
    [...model.functions, ...model.classes.flatMap((entry) => entry.methods)]
      .filter((fn) => fn.deprecated)
      .map((fn) => ({ fn, ref: `${ROUTE}/${model.config.slug}#${anchorOf(model.config.deprecatedTitle ?? 'Deprecated')}` })),
  );
  if (globals.length || values.length) {
    types.push(
      drop({
        id: GLOBALS,
        name: GLOBALS,
        title: 'Global functions',
        kind: 'globals',
        group: groupOf(GLOBALS, [...globals, ...values][0].file).id,
        text: 'Functions and values every mod has. Use them by name, with nothing in front.',
        props: values.map((value) =>
          drop({
            id: value.name,
            name: value.name,
            type: value.type,
            text: value.description,
            next: value.next,
            ref: `${ROUTE}/${value.page}#${anchorOf(value.name)}`,
            guide: guide(first(MEMBER_GUIDES, value.name)),
            use: `print(${value.name})`,
          }),
        ),
        funcs: globals.map((fn) => functionRow(fn)),
      }),
    );
    for (const item of [...globals, ...values]) groupOf(item.name, item.file).members.push(item.name);
  }
  if (blocked.length) {
    const config = models.find((model) => model.config.deprecatedIntro)?.config;
    types.push({
      id: BLOCKED,
      name: BLOCKED,
      title: config?.deprecatedTitle ?? 'Deprecated',
      kind: 'blocked',
      group: groupOf(BLOCKED, blocked[0].fn.file).id,
      text: config?.deprecatedIntro ?? '',
      ref: blocked[0].ref,
      funcs: blocked.map(({ fn, ref }) => ({ ...functionRow(fn), ref, blocked: true })),
    });
    groupOf(BLOCKED, blocked[0].fn.file).types.push(BLOCKED);
  }

  // In a group: the types its page leads with, then tables of functions, objects, plain tables and named values.
  const order = { namespace: 0, object: 1, data: 2, alias: 3, blocked: 4 };
  const lead = new Set(models.flatMap((model) => model.config.lead ?? []).filter((name) => classes.has(name)).map((name) => typeId(classes.get(name))));
  const kindOf = new Map(types.map((type) => [type.id, type.kind]));
  for (const group of groups) {
    const at = new Map(group.types.map((id, index) => [id, index]));
    group.types.sort((a, b) => Number(lead.has(b)) - Number(lead.has(a)) || order[kindOf.get(a)] - order[kindOf.get(b)] || at.get(a) - at.get(b));
  }

  return { groups: groups.filter((group) => group.types.length || group.members.length), spoken, types };
}

// ---------------------------------------------------------------------------------------------

// Only the files directly in the folder are Wax's own. Its `icarus` folder holds the game's classes, which the Explorer shows from the game index.
const sources = fs
  .readdirSync(TYPES, { withFileTypes: true })
  .filter((entry) => entry.isFile() && entry.name.endsWith('.lua') && !SKIP.has(entry.name))
  .map((entry) => entry.name)
  .sort((a, b) => {
    const order = Object.keys(PAGES);
    const [ia, ib] = [order.indexOf(a), order.indexOf(b)];
    return (ia === -1 ? order.length : ia) - (ib === -1 ? order.length : ib) || a.localeCompare(b);
  });

const models = sources.map((name) => parseFile(name, fs.readFileSync(path.join(TYPES, name), 'utf8')));
const { files, marks, compared, explorer } = build(models);

fs.mkdirSync(OUT, { recursive: true });
let written = 0;
const outputs = [...files].map(([name, content]) => [path.join(OUT, name), content]);
outputs.push([EXPLORER_OUT, `${JSON.stringify(explorer, null, 1)}\n`]);
for (const [target, content] of outputs) {
  if (fs.existsSync(target) && fs.readFileSync(target, 'utf8') === content) continue;
  fs.writeFileSync(target, content);
  written++;
}
// A generated page whose type file is gone goes too; hand-written pages are left alone.
for (const name of fs.readdirSync(OUT)) {
  if (!name.endsWith('.mdx') || files.has(name)) continue;
  const target = path.join(OUT, name);
  if (fs.readFileSync(target, 'utf8').includes(MARKER)) {
    fs.rmSync(target);
    console.log(`[generate-api] removed ${name} (its type file no longer exists)`);
  }
}

const count = (pick) => models.reduce((sum, model) => sum + pick(model), 0);
console.log(
  `[generate-api] ${files.size} pages from ${sources.join(', ')}: ` +
    `${count((m) => m.classes.length)} classes, ` +
    `${count((m) => m.functions.length + m.classes.reduce((n, c) => n + c.methods.length, 0))} functions, ` +
    `${count((m) => m.aliases.length)} aliases; ${written} file(s) changed.`,
);
console.log(
  compared
    ? `[generate-api] compared with the released types in ${path.relative(DOCS, RELEASED_TYPES)}: ` +
        `${models.filter((model) => model.next).length} page(s) are new as a whole, ${marks} entries on the other pages are marked as newer.`
    : `[generate-api] ${path.relative(DOCS, RELEASED_TYPES)} has no type files: nothing is marked as newer than the released Wax.`,
);
if (SKIP.size) console.log(`[generate-api] skipped on purpose: ${[...SKIP].join(', ')}`);
if (bare.length) console.log(`[generate-api] ${bare.length} class(es) or function(s) have no description in the type files: ${bare.join(', ')}`);
if (notes.length) {
  console.log(`[generate-api] ${notes.length} thing(s) could not be used as written:`);
  for (const line of notes) console.log(`  ${line}`);
}
