#!/usr/bin/env node
// Writes content/docs/reference/*.mdx from the LuaLS annotations in wax/types/*.lua.
// Runs before `dev` and `build`. When the type files are not there (the published repository
// holds only this folder) it does nothing, and the committed pages are used as they are.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DOCS = path.resolve(HERE, '..');
const TYPES = process.env.WAX_TYPES_DIR
  ? path.resolve(process.env.WAX_TYPES_DIR)
  : path.resolve(DOCS, '..', 'wax', 'types');
const OUT = path.join(DOCS, 'content', 'docs', 'reference');
const ROUTE = '/docs/reference';
const MARKER = 'Generated by scripts/generate-api.mjs';

// One page per type file. A file not listed here still gets a page, named after the file.
const PAGES = {
  'ui.lua': {
    slug: 'ui',
    icon: 'PanelTop',
    title: 'ui',
    description: 'Windows, overlays, notifications, hotkeys, themes and icons: everything under ui.',
    lead: ['WaxUI'],
  },
  'controls.lua': {
    slug: 'controls',
    icon: 'SlidersHorizontal',
    title: 'Controls',
    description: 'Every control you can add to a window, a page, a section, a row or an overlay.',
    lead: ['WaxContainer', 'WaxControl'],
  },
  'game.lua': {
    slug: 'game',
    icon: 'Globe',
    title: 'game',
    description: 'The game object tree: game, game.Players and the Instances they hand out.',
    lead: ['WaxGame'],
  },
  'task.lua': {
    slug: 'tasks',
    icon: 'Timer',
    title: 'Tasks and signals',
    description: 'task for running code alongside the game, and Signal for events.',
    lead: ['WaxTask'],
  },
  'mod.lua': {
    slug: 'mods',
    icon: 'Package',
    title: 'Mods',
    description: 'What every mod has: mod, log, print, persist, storage, require and raw.',
    deprecatedTitle: 'Blocked functions',
    deprecatedIntro:
      'These UE4SS functions raise an error when a mod calls them. The reason is given for each one.',
  },
};
// Lua's own standard library, written by the language server. Not part of Wax.
const SKIP = new Set(['lua_basic.lua']);
const IGNORED_TAGS = new Set(['meta']);

if (!fs.existsSync(TYPES)) {
  console.log(`[generate-api] ${path.relative(DOCS, TYPES)} not found: keeping the reference pages that are already here.`);
  process.exit(0);
}

const notes = [];
const note = (file, line, text) => notes.push(`${file}:${line}: ${text}`);
const bare = [];

// ---------------------------------------------------------------------------------------------
// Reading types such as `fun(self: WaxSignal<F>, fn: F): WaxConnection` or `"a"|"b"|string`.

const CLOSER = { '(': ')', '{': '}', '[': ']', '<': '>' };

function skipSpaces(text, at) {
  while (at < text.length && (text[at] === ' ' || text[at] === '\t')) at++;
  return at;
}

function closeQuote(text, at) {
  const quote = text[at];
  let i = at + 1;
  while (i < text.length && text[i] !== quote) i += text[i] === '\\' ? 2 : 1;
  return Math.min(i + 1, text.length);
}

function closeBracket(text, at) {
  const stack = [CLOSER[text[at]]];
  let i = at + 1;
  while (i < text.length && stack.length) {
    const c = text[i];
    if (c === '"' || c === "'") {
      i = closeQuote(text, i);
      continue;
    }
    if (c === stack[stack.length - 1]) stack.pop();
    else if (CLOSER[c] && !(c === '<' && !/[\w>]/.test(text[i - 1] ?? ''))) stack.push(CLOSER[c]);
    i++;
  }
  return i;
}

function readMember(text, at) {
  let i = at;
  if (text.startsWith('...', i)) {
    i += 3;
    return i < text.length && /[\w"'({[]/.test(text[i]) ? readMember(text, i) : i;
  }
  const c = text[i];
  if (c === '"' || c === "'") i = closeQuote(text, i);
  else if (c === '{' || c === '(' || c === '[') i = closeBracket(text, i);
  else if (text.startsWith('fun(', i)) {
    i = closeBracket(text, i + 3);
    const colon = skipSpaces(text, i);
    if (text[colon] === ':') {
      i = readType(text, skipSpaces(text, colon + 1));
      while (text[i] === ',') i = readType(text, skipSpaces(text, i + 1));
    }
  } else {
    const word = /^[A-Za-z_][\w.]*/.exec(text.slice(i));
    if (!word) return at;
    i += word[0].length;
    if (text[i] === '<') i = closeBracket(text, i);
  }
  for (;;) {
    if (text.startsWith('[]', i)) i += 2;
    else if (text[i] === '?') i += 1;
    else break;
  }
  return i;
}

// Returns the index just past the type that starts at `at` (equal to `at` when there is none).
function readType(text, at) {
  let i = readMember(text, at);
  if (i === at) return at;
  for (;;) {
    const bar = skipSpaces(text, i);
    if (text[bar] !== '|') return i;
    const next = readMember(text, skipSpaces(text, bar + 1));
    if (next === skipSpaces(text, bar + 1)) return i;
    i = next;
  }
}

function splitTopLevel(text, separator) {
  const parts = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (c === '"' || c === "'") {
      i = closeQuote(text, i) - 1;
      continue;
    }
    if (CLOSER[c] && !(c === '<' && !/[\w>]/.test(text[i - 1] ?? ''))) depth++;
    else if (c === ')' || c === '}' || c === ']' || (c === '>' && depth > 0 && text[i - 1] !== '-')) depth--;
    else if (c === separator && depth === 0) {
      parts.push(text.slice(start, i).trim());
      start = i + 1;
    }
  }
  parts.push(text.slice(start).trim());
  return parts.filter((part) => part !== '');
}

// ---------------------------------------------------------------------------------------------
// Parsing one type file.

function parseFile(file, source) {
  const model = { file, classes: [], aliases: [], functions: [], values: [], tables: new Map() };
  const lines = source.split(/\r?\n/);
  let block = null;

  const newBlock = () => ({
    text: [],
    classes: [],
    aliases: [],
    alias: null,
    params: [],
    returns: [],
    generics: [],
    overloads: [],
    type: null,
    deprecated: false,
    hasFunctionTags: false,
  });
  const takeText = () => {
    const text = block.text.join(' ').replace(/\s+/g, ' ').trim();
    block.text = [];
    return text;
  };

  function tag(name, rest, line) {
    switch (name) {
      case 'class': {
        const match = /^([\w.]+)\s*(<[^>]*>)?\s*(?::\s*(.+))?$/.exec(rest);
        if (!match) return note(file, line, `could not read @class "${rest}"`);
        const entry = {
          name: match[1],
          generics: match[2] ? match[2].slice(1, -1).split(',').map((part) => part.trim()) : [],
          parents: match[3] ? splitTopLevel(match[3], ',') : [],
          description: takeText(),
          fields: [],
          methods: [],
          bound: null,
          file,
          line,
        };
        block.classes.push(entry);
        block.alias = null;
        return;
      }
      case 'field': {
        const owner = block.classes[block.classes.length - 1];
        if (!owner) return note(file, line, '@field outside a class');
        let text = rest.replace(/^(public|private|protected|package)\s+/, '');
        let fieldName;
        if (text[0] === '[') {
          const end = closeBracket(text, 0);
          fieldName = text.slice(0, end);
          text = text.slice(end);
        } else {
          const match = /^(\S+)/.exec(text);
          fieldName = match ? match[1] : '';
          text = text.slice(fieldName.length);
        }
        const optional = fieldName.endsWith('?');
        if (optional) fieldName = fieldName.slice(0, -1);
        const start = skipSpaces(text, 0);
        const end = readType(text, start);
        if (!fieldName || end === start) return note(file, line, `could not read @field "${rest}"`);
        owner.fields.push({
          name: fieldName,
          optional,
          type: text.slice(start, end),
          description: text.slice(end).trim(),
          line,
        });
        return;
      }
      case 'param': {
        const match = /^(\.\.\.|[\w]+)(\?)?\s+/.exec(rest);
        if (!match) return note(file, line, `could not read @param "${rest}"`);
        const start = match[0].length;
        const end = readType(rest, start);
        if (end === start) return note(file, line, `@param ${match[1]} has no type`);
        block.params.push({
          name: match[1],
          optional: Boolean(match[2]),
          type: rest.slice(start, end),
          description: rest.slice(end).trim(),
        });
        block.hasFunctionTags = true;
        return;
      }
      case 'return': {
        const end = readType(rest, 0);
        if (end === 0) return note(file, line, `could not read @return "${rest}"`);
        let tail = rest.slice(end).trim();
        let returnName = '';
        // LuaLS reads the first word as the value's name; a capitalised word is taken as prose instead.
        const word = /^([a-z_]\w*)(?:\s+|$)/.exec(tail);
        if (tail.startsWith('#')) tail = tail.slice(1).trim();
        else if (word) {
          returnName = word[1];
          tail = tail.slice(word[0].length).replace(/^#\s*/, '').trim();
        }
        block.returns.push({ type: rest.slice(0, end), name: returnName, description: tail });
        block.hasFunctionTags = true;
        return;
      }
      case 'alias': {
        const match = /^([\w.]+)\s*(.*)$/.exec(rest);
        if (!match) return note(file, line, `could not read @alias "${rest}"`);
        const entry = { name: match[1], type: match[2].trim(), members: [], description: takeText(), file, line };
        if (entry.type) {
          const end = readType(entry.type, 0);
          if (end !== entry.type.length) note(file, line, `@alias ${entry.name}: text after the type was dropped ("${entry.type.slice(end).trim()}")`);
          entry.type = entry.type.slice(0, end);
        }
        block.aliases.push(entry);
        block.alias = entry;
        return;
      }
      case 'generic':
        for (const part of splitTopLevel(rest, ',')) block.generics.push(part);
        block.hasFunctionTags = true;
        return;
      case 'overload':
        block.overloads.push(rest.trim());
        block.hasFunctionTags = true;
        return;
      case 'type':
        block.type = rest.trim();
        return;
      case 'deprecated':
        block.deprecated = true;
        return;
      default:
        if (!IGNORED_TAGS.has(name)) note(file, line, `@${name} is not handled and was left out`);
    }
  }

  function flush(codeLine, line) {
    if (!block) return;
    const current = block;
    block = null;
    for (const entry of current.classes) model.classes.push(entry);
    for (const entry of current.aliases) model.aliases.push(entry);
    const text = current.text.join(' ').replace(/\s+/g, ' ').trim();

    const fn = /^(?:local\s+)?function\s+([\w.:]+)\s*\(([^)]*)\)/.exec(codeLine);
    if (fn) {
      const full = fn[1];
      const cut = Math.max(full.lastIndexOf('.'), full.lastIndexOf(':'));
      const args = fn[2].split(',').map((part) => part.trim()).filter(Boolean);
      const known = new Map(current.params.map((param) => [param.name, param]));
      for (const arg of args) {
        if (!known.has(arg)) note(file, line, `${full}: parameter "${arg}" has no @param`);
      }
      for (const param of current.params) {
        if (!args.includes(param.name)) note(file, line, `${full}: @param "${param.name}" is not in the function's argument list`);
      }
      if (!text && !current.deprecated) bare.push(full);
      model.functions.push({
        table: cut === -1 ? null : full.slice(0, cut),
        separator: cut === -1 ? '' : full[cut],
        name: cut === -1 ? full : full.slice(cut + 1),
        args,
        params: known,
        returns: current.returns,
        generics: current.generics,
        overloads: current.overloads,
        deprecated: current.deprecated,
        description: text,
        file,
        line,
      });
      return;
    }

    const assignment = /^(local\s+)?([A-Za-z_]\w*)\s*=\s*(.+?)\s*$/.exec(codeLine);
    if (assignment) {
      const variable = assignment[2];
      const isTable = /^\{\s*\}$/.test(assignment[3]);
      const owner = current.classes[current.classes.length - 1];
      if (owner && isTable) {
        owner.bound = { name: variable, global: !assignment[1] };
        model.tables.set(variable, owner.name);
        if (text) note(file, line, `text between @class ${owner.name} and "${variable} = {}" was dropped`);
      } else if (!assignment[1]) {
        model.values.push({ name: variable, type: current.type ?? 'any', description: text, file, line });
      }
      if (current.hasFunctionTags) note(file, line, `@param/@return/@generic/@overload above "${variable}" do not belong to a function and were dropped`);
      return;
    }

    if (current.hasFunctionTags) note(file, line, 'annotations for a function are not followed by one and were dropped');
    if (text && current.classes.length === 0 && current.aliases.length === 0) {
      note(file, line, `a comment that documents nothing was dropped ("${text.slice(0, 50)}")`);
    }
    if (codeLine.trim() !== '' && !codeLine.trim().startsWith('--')) note(file, line, `this line was not understood: ${codeLine.trim().slice(0, 60)}`);
  }

  lines.forEach((raw, index) => {
    const line = index + 1;
    if (raw.startsWith('---')) {
      block ??= newBlock();
      const body = raw.slice(3);
      if (body.startsWith('@')) {
        const match = /^@(\w+)\s*(.*)$/.exec(body);
        if (match) tag(match[1], match[2].trim(), line);
        else note(file, line, `could not read "${body}"`);
      } else if (body.startsWith('|')) {
        if (!block.alias) return note(file, line, 'a "---|" line outside an @alias');
        const match = /^\|[>+]?\s*(.+?)(?:\s+#\s*(.*))?$/.exec(body);
        if (match) block.alias.members.push({ value: match[1].trim(), description: (match[2] ?? '').trim() });
      } else {
        block.text.push(body.trim());
      }
      return;
    }
    if (block) flush(raw, line);
    else if (raw.trim() !== '' && !raw.trim().startsWith('--')) {
      // A line with no annotations above it: still record what it declares.
      block = newBlock();
      flush(raw, line);
    }
  });
  if (block) flush('', lines.length);

  for (const fn of model.functions) {
    if (fn.table === null) continue;
    const owner = model.classes.find((entry) => entry.name === model.tables.get(fn.table));
    if (owner) owner.methods.push(fn);
    else note(file, fn.line, `${fn.table}${fn.separator}${fn.name}: "${fn.table}" is not a table declared after a @class`);
  }
  model.functions = model.functions.filter((fn) => fn.table === null);
  return model;
}

// ---------------------------------------------------------------------------------------------
// Working out how each thing is reached from a mod, and where it is documented.

const lowerFirst = (text) => text.charAt(0).toLowerCase() + text.slice(1);
const anchorOf = (text) => text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const isSignal = (type) => /^WaxSignal\b/.test(type);
const selfMethod = (field) => /^fun\(\s*self\b/.test(field.type);

function resolve(models) {
  const classes = new Map();
  for (const model of models) for (const entry of model.classes) classes.set(entry.name, entry);

  // A table bound to a global is reached by that name; a class that is a field of one, through it.
  for (const entry of classes.values()) {
    if (entry.bound?.global) entry.path = entry.bound.name;
  }
  // Only when exactly one such field has that type: `game.World` is one of many Instances, not "the" Instance.
  const reached = new Map();
  for (const owner of classes.values()) {
    if (!owner.bound?.global) continue;
    for (const field of owner.fields) {
      if (!classes.has(field.type)) continue;
      reached.set(field.type, [...(reached.get(field.type) ?? []), `${owner.path}.${field.name}`]);
    }
  }
  for (const [name, paths] of reached) {
    const target = classes.get(name);
    if (paths.length === 1 && !target.path) target.path = paths[0];
  }

  const isObject = (entry, seen = new Set()) => {
    if (seen.has(entry.name)) return false;
    seen.add(entry.name);
    if (entry.methods.length > 0 || entry.bound) return true;
    if (entry.fields.some((field) => isSignal(field.type) || selfMethod(field))) return true;
    return entry.parents.some((parent) => classes.has(parent) && isObject(classes.get(parent), seen));
  };

  for (const entry of classes.values()) {
    entry.kind = entry.path ? 'namespace' : isObject(entry) ? 'object' : 'data';
    if (!entry.description && !/(Options|Settings)$/.test(entry.name)) bare.push(entry.name);
    entry.heading = entry.path ?? entry.name;
    entry.anchor = anchorOf(entry.path ?? entry.name);
    entry.subject = entry.path ?? lowerFirst(entry.bound?.name ?? entry.name.replace(/^Wax/, ''));
    // Fields written as `fun(self: ...)` are methods.
    for (const field of entry.fields.filter(selfMethod)) {
      const open = field.type.indexOf('(');
      const close = closeBracket(field.type, open);
      const inner = splitTopLevel(field.type.slice(open + 1, close - 1), ',').slice(1);
      const args = [];
      const params = new Map();
      for (const part of inner) {
        const match = /^(\.\.\.|\w+)(\?)?\s*:\s*(.+)$/.exec(part);
        const argName = match ? match[1] : part;
        args.push(argName);
        params.set(argName, { name: argName, optional: Boolean(match?.[2]), type: match ? match[3] : 'any', description: '' });
      }
      const after = field.type.slice(close).replace(/^\s*:\s*/, '').trim();
      entry.methods.push({
        table: entry.name,
        separator: ':',
        name: field.name,
        args,
        params,
        returns: after ? splitTopLevel(after, ',').map((type) => ({ type, name: '', description: '' })) : [],
        generics: [],
        overloads: [],
        deprecated: false,
        description: field.description,
        file: entry.file,
        line: field.line,
      });
    }
    entry.fields = entry.fields.filter((field) => !selfMethod(field));
    for (const fn of entry.methods) {
      fn.owner = entry;
      fn.display = `${entry.subject}${fn.separator}${fn.name}`;
    }
  }
  return classes;
}

// ---------------------------------------------------------------------------------------------
// Writing MDX.

function escapeText(text, inTable) {
  // Outside `code`, the characters MDX would read as JSX or an expression are escaped.
  return text
    .split(/(`[^`]*`)/)
    .map((part, index) => {
      let out = index % 2 === 1 ? part : part.replace(/[{}<]/g, (c) => `\\${c}`);
      if (inTable) out = out.replace(/\|/g, '\\|');
      return out;
    })
    .join('');
}

function build(models) {
  const classes = resolve(models);
  const pageOf = new Map();
  for (const model of models) {
    const config = PAGES[model.file] ?? {
      slug: anchorOf(path.basename(model.file, '.lua')),
      title: path.basename(model.file, '.lua'),
      description: `Generated from ${model.file}.`,
    };
    model.config = config;
    for (const entry of model.classes) pageOf.set(entry.name, config.slug);
    for (const entry of model.aliases) pageOf.set(entry.name, config.slug);
  }

  const aliases = new Map();
  for (const model of models) for (const entry of model.aliases) aliases.set(entry.name, entry);
  const targetOf = (name) => {
    if (classes.has(name)) return `${ROUTE}/${pageOf.get(name)}#${classes.get(name).anchor}`;
    if (aliases.has(name)) return `${ROUTE}/${pageOf.get(name)}#${anchorOf(name)}`;
    return null;
  };

  // Every function by the names prose uses for it: "ui.Notify", "Window:StatusBar", "game:GetTagged".
  const spoken = new Map();
  const allFunctions = [];
  for (const model of models) {
    for (const fn of model.functions) {
      fn.display = fn.name;
      fn.anchor = anchorOf(fn.name);
      fn.page = model.config.slug;
      allFunctions.push(fn);
    }
    for (const entry of model.classes) {
      for (const fn of entry.methods) {
        fn.anchor = anchorOf(fn.display);
        fn.page = model.config.slug;
        allFunctions.push(fn);
        const href = `${ROUTE}/${fn.page}#${fn.anchor}`;
        if (entry.path) spoken.set(fn.display, href);
        if (entry.bound && !entry.path) spoken.set(`${entry.bound.name}${fn.separator}${fn.name}`, href);
      }
    }
  }
  const spokenPattern = spoken.size
    ? new RegExp(
        `(?<![\\w.:])(${[...spoken.keys()].sort((a, b) => b.length - a.length).map((key) => key.replace(/[.]/g, '\\.')).join('|')})(\\([^()\\s]*\\)(?:\\.\\w+)*)?(?![\\w(])`,
        'g',
      )
    : null;

  const prose = (text, inTable, selfHref) => {
    if (!text) return '';
    const linked = text
      .split(/(`[^`]*`)/)
      .map((part, index) => {
        if (index % 2 === 1 || !spokenPattern) return part;
        return part.replace(spokenPattern, (whole, name) => {
          const href = spoken.get(name);
          return href === selfHref ? `\`${whole}\`` : `[\`${whole}\`](${href})`;
        });
      })
      .join('');
    return escapeText(linked, inTable);
  };

  const code = (text, inTable) => `\`${inTable ? text.replace(/\|/g, '\\|') : text}\``;
  // A type for a table cell or a sentence: each member of a union on its own, linked when it is documented.
  const typeLinks = (type, inTable) =>
    splitTopLevel(type, '|')
      .map((member) => {
        const match = /^([\w.]+)((?:\[\]|\?)*)$/.exec(member);
        const href = match && targetOf(match[1]);
        return href ? `[${code(member, inTable)}](${href})` : code(member, inTable);
      })
      .join(inTable ? ' \\| ' : ' | ');

  // A table; its last column is left out when every row leaves it empty.
  const table = (out, headers, rows) => {
    if (!rows.length) return;
    const last = headers.length - 1;
    const keep = rows.some((row) => row[last] !== '') ? headers.length : last;
    out.push(`| ${headers.slice(0, keep).join(' | ')} |`, `| ${headers.slice(0, keep).map(() => '---').join(' | ')} |`);
    for (const row of rows) out.push(`| ${row.slice(0, keep).join(' | ')} |`);
    out.push('');
  };
  // A member with no text of its own is described by the class it holds.
  const fieldText = (field) => field.description || classes.get(field.type)?.description || '';

  const mentions = (type, name) => new RegExp(`(?<![\\w.])${name}(?![\\w.])`).test(type);
  const fnLink = (fn) => `[\`${fn.display}\`](${ROUTE}/${fn.page}#${fn.anchor})`;

  function writeFunction(out, fn, level, used) {
    const args = fn.args.map((arg) => `${arg}${fn.params.get(arg)?.optional ? '?' : ''}`);
    let anchor = fn.anchor;
    for (let n = 2; used.has(anchor); n++) anchor = `${fn.anchor}-${n}`;
    if (anchor !== fn.anchor) note(fn.file, fn.line, `${fn.display} shares its anchor with something else; it became #${anchor}`);
    used.add(anchor);
    fn.anchor = anchor;
    out.push(`${'#'.repeat(level)} \`${fn.display}(${args.join(', ')})\` [#${anchor}]`, '');
    if (fn.description) out.push(prose(fn.description, false, `${ROUTE}/${fn.page}#${anchor}`), '');

    const generics = fn.generics.length ? `<${fn.generics.join(', ')}>` : '';
    const typed = fn.args.map((arg) => {
      const param = fn.params.get(arg);
      return `${arg}${param?.optional ? '?' : ''}: ${param?.type ?? 'any'}`;
    });
    const result = fn.returns.length ? `: ${fn.returns.map((entry) => entry.type).join(', ')}` : '';
    out.push('```lua', `${fn.display}${generics}(${typed.join(', ')})${result}`);
    for (const overload of fn.overloads) {
      // On a method written with a colon, the overload's `self` is the object in front of the colon.
      const shape = overload.replace(/^fun/, '');
      out.push(`${fn.display}${fn.separator === ':' ? shape.replace(/^\(\s*self\s*:\s*[\w.<>]+\s*,?\s*/, '(') : shape}`);
    }
    out.push('```', '');

    table(
      out,
      ['Parameter', 'Type', 'Description'],
      fn.args.map((arg) => {
        const param = fn.params.get(arg);
        return [`${code(arg, true)}${param?.optional ? ' (optional)' : ''}`, typeLinks(param?.type ?? 'any', true), prose(param?.description ?? '', true)];
      }),
    );
    if (fn.returns.length === 1) {
      const entry = fn.returns[0];
      const detail = [entry.name ? `(${code(entry.name)})` : '', prose(entry.description)].filter(Boolean).join(' ');
      out.push(`**Returns** ${typeLinks(entry.type)}${detail ? ` ${detail}` : ''}`, '');
    } else if (fn.returns.length > 1) {
      out.push('**Returns**', '');
      for (const entry of fn.returns) {
        out.push(`- ${typeLinks(entry.type)}${entry.name ? ` (${code(entry.name)})` : ''}${entry.description ? ` ${prose(entry.description)}` : ''}`);
      }
      out.push('');
    } else {
      out.push('**Returns** nothing.', '');
    }
  }

  function writeFields(out, fields, heading) {
    table(
      out,
      [heading, 'Type', 'Description'],
      fields.map((field) => {
        const label = field.name.startsWith('[') ? `any other key (${code(field.name, true)})` : code(field.name, true);
        const required = heading === 'Option' && !field.optional && !field.name.startsWith('[') ? ' (required)' : '';
        const optional = heading !== 'Option' && field.optional ? ' (optional)' : '';
        return [`${label}${required}${optional}`, typeLinks(field.type, true), prose(fieldText(field), true)];
      }),
    );
  }

  function writeClass(out, entry, used) {
    used.add(entry.anchor);
    out.push(`## ${entry.kind === 'namespace' ? `\`${entry.heading}\`` : entry.heading} [#${entry.anchor}]`, '');
    if (entry.description) out.push(prose(entry.description), '');

    const facts = [];
    if (entry.kind === 'namespace') facts.push(`Type name: ${code(entry.name)}.`);
    const parents = entry.parents.filter((parent) => parent !== 'WaxOptions');
    if (parents.length) {
      const list = parents.map((parent) => (targetOf(parent) ? `[${code(parent)}](${targetOf(parent)})` : code(parent))).join(', ');
      facts.push(entry.kind === 'data' ? `Extends ${list}.` : `It can also do everything ${list} can.`);
    }
    const listed = (functions) => `${functions.slice(0, 8).map(fnLink).join(', ')}${functions.length > 8 ? ' and others' : ''}`;
    if (entry.kind !== 'namespace') {
      const makers = allFunctions.filter((fn) => fn.owner !== entry && !fn.deprecated && fn.returns.some((value) => mentions(value.type, entry.name)));
      if (makers.length) facts.push(`${entry.kind === 'object' ? 'You get one from' : 'Returned by'} ${listed(makers)}.`);
    }
    if (entry.kind === 'object' && entry.methods.length) facts.push(`Below, ${code(entry.subject)} stands for one of these.`);
    if (entry.kind === 'data') {
      const users = allFunctions.filter((fn) => !fn.deprecated && [...fn.params.values()].some((param) => mentions(param.type, entry.name)));
      if (users.length) facts.push(`Used by ${listed(users)}.`);
    }
    if (facts.length) out.push(facts.join(' '), '');

    const signals = entry.fields.filter((field) => isSignal(field.type));
    const others = entry.fields.filter((field) => !isSignal(field.type));
    if (entry.kind === 'data') {
      const options = /(Options|Settings)$/.test(entry.name) || entry.parents.includes('WaxOptions');
      writeFields(out, others, options ? 'Option' : 'Field');
    } else {
      writeFields(out, others, entry.kind === 'namespace' ? 'Member' : 'Property');
    }
    table(
      out,
      ['Signal', 'Handler receives', 'Description'],
      signals.map((field) => {
        const shape = /^WaxSignal<fun\((.*)\)>$/.exec(field.type);
        const receives = !shape ? 'depends on the control' : shape[1].trim() === '' ? 'nothing' : code(shape[1].trim(), true);
        return [code(field.name, true), receives, prose(field.description, true)];
      }),
    );
    for (const fn of entry.methods.filter((method) => !method.deprecated)) writeFunction(out, fn, 3, used);
  }

  function writeAlias(out, entry, used) {
    used.add(anchorOf(entry.name));
    out.push(`### ${entry.name} [#${anchorOf(entry.name)}]`, '');
    if (entry.description) out.push(prose(entry.description), '');
    const members = entry.members.length
      ? entry.members
      : splitTopLevel(entry.type, '|').length > 1
        ? splitTopLevel(entry.type, '|').map((value) => ({ value, description: '' }))
        : [];
    if (members.length === 0) {
      out.push(`The same as ${typeLinks(entry.type)}.`, '');
    } else if (members.some((member) => member.description)) {
      table(out, ['Value', 'Description'], members.map((member) => [code(member.value, true), prose(member.description, true)]));
    } else {
      const literal = members.filter((member) => /^["']/.test(member.value));
      const open = members.filter((member) => !/^["']/.test(member.value));
      const list = literal.map((member) => code(member.value)).join(', ');
      const rest = open.map((member) => typeLinks(member.value)).join(' or ');
      out.push(literal.length ? `One of ${list}${rest ? `, or any other ${rest}` : ''}.` : `One of ${rest}.`, '');
    }
  }

  const files = new Map();
  for (const model of models) {
    const config = model.config;
    const out = [
      '---',
      `title: ${JSON.stringify(config.title)}`,
      `description: ${JSON.stringify(config.description)}`,
      ...(config.icon ? [`icon: ${config.icon}`] : []),
      '---',
      '',
      `{/* ${MARKER} from wax/types/${model.file}. Do not edit: change the type file and run "npm run generate". */}`,
      '',
    ];
    const used = new Set();
    const lead = (config.lead ?? []).map((name) => model.classes.find((entry) => entry.name === name)).filter(Boolean);
    const rest = model.classes.filter((entry) => !lead.includes(entry));
    const ordered = [
      ...lead,
      ...rest.filter((entry) => entry.kind === 'namespace' && entry.bound?.global),
      ...rest.filter((entry) => entry.kind === 'namespace' && !entry.bound?.global),
    ];
    for (const entry of ordered) writeClass(out, entry, used);

    const live = model.functions.filter((fn) => !fn.deprecated);
    if (live.length) {
      out.push('## Global functions [#global-functions]', '', 'Call these by name, with nothing in front.', '');
      for (const fn of live) writeFunction(out, fn, 3, used);
    }
    if (model.values.length) {
      out.push('## Global values [#global-values]', '');
      for (const value of model.values) {
        used.add(anchorOf(value.name));
        out.push(`### \`${value.name}\` [#${anchorOf(value.name)}]`, '');
        if (value.description) out.push(prose(value.description), '');
        out.push(`**Type** ${typeLinks(value.type)}`, '');
      }
    }

    for (const entry of rest.filter((item) => item.kind === 'object')) writeClass(out, entry, used);
    for (const entry of rest.filter((item) => item.kind === 'data')) writeClass(out, entry, used);

    if (model.aliases.length) {
      out.push('## Named values [#named-values]', '', 'Short names for a fixed set of values. Where a function asks for one of these, pass one of the values listed.', '');
      for (const entry of model.aliases) writeAlias(out, entry, used);
    }

    const blocked = [...model.functions, ...model.classes.flatMap((entry) => entry.methods)].filter((fn) => fn.deprecated);
    if (blocked.length) {
      out.push(`## ${config.deprecatedTitle ?? 'Deprecated'} [#${anchorOf(config.deprecatedTitle ?? 'Deprecated')}]`, '');
      if (config.deprecatedIntro) out.push(config.deprecatedIntro, '');
      table(out, ['Function', 'Note'], blocked.map((fn) => [code(fn.display, true), prose(fn.description, true)]));
    }

    out.push('---', '', '*This page is written by a script from the type definitions that ship with Wax, so it always matches them.*', '');
    files.set(`${config.slug}.mdx`, out.join('\n'));
  }
  return files;
}

// ---------------------------------------------------------------------------------------------

const sources = fs
  .readdirSync(TYPES)
  .filter((name) => name.endsWith('.lua') && !SKIP.has(name))
  .sort((a, b) => {
    const order = Object.keys(PAGES);
    const [ia, ib] = [order.indexOf(a), order.indexOf(b)];
    return (ia === -1 ? order.length : ia) - (ib === -1 ? order.length : ib) || a.localeCompare(b);
  });

const models = sources.map((name) => parseFile(name, fs.readFileSync(path.join(TYPES, name), 'utf8')));
const files = build(models);

fs.mkdirSync(OUT, { recursive: true });
let written = 0;
for (const [name, content] of files) {
  const target = path.join(OUT, name);
  if (fs.existsSync(target) && fs.readFileSync(target, 'utf8') === content) continue;
  fs.writeFileSync(target, content);
  written++;
}
// A generated page whose type file is gone goes too; hand-written pages are left alone.
for (const name of fs.readdirSync(OUT)) {
  if (!name.endsWith('.mdx') || files.has(name)) continue;
  const target = path.join(OUT, name);
  if (fs.readFileSync(target, 'utf8').includes(MARKER)) {
    fs.rmSync(target);
    console.log(`[generate-api] removed ${name} (its type file no longer exists)`);
  }
}

const count = (pick) => models.reduce((sum, model) => sum + pick(model), 0);
console.log(
  `[generate-api] ${files.size} pages from ${sources.join(', ')}: ` +
    `${count((m) => m.classes.length)} classes, ` +
    `${count((m) => m.functions.length + m.classes.reduce((n, c) => n + c.methods.length, 0))} functions, ` +
    `${count((m) => m.aliases.length)} aliases; ${written} file(s) changed.`,
);
if (SKIP.size) console.log(`[generate-api] skipped on purpose: ${[...SKIP].join(', ')}`);
if (bare.length) console.log(`[generate-api] ${bare.length} class(es) or function(s) have no description in the type files: ${bare.join(', ')}`);
if (notes.length) {
  console.log(`[generate-api] ${notes.length} thing(s) could not be used as written:`);
  for (const line of notes) console.log(`  ${line}`);
}
